<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'behat.mink.default_session' shared service.

if ($lazyLoad) {
    return $this->services['behat.mink.default_session'] = $this->createProxy('Session_4e1eb92', function () {
        return \Session_4e1eb92::staticProxyConstructor(function (&$wrappedInstance, \ProxyManager\Proxy\LazyLoadingInterface $proxy) {
            $wrappedInstance = $this->load('getBehat_Mink_DefaultSessionService.php', false);

            $proxy->setProxyInitializer(null);

            return true;
        });
    });
}

include_once \dirname(__DIR__, 4).'/vendor/friends-of-behat/mink/src/Session.php';

return ($this->services['behat.mink'] ?? $this->load('getBehat_MinkService.php'))->getSession();
