<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'fos_rest.error_listener' shared service.

include_once \dirname(__DIR__, 4).'/vendor/symfony/http-kernel/EventListener/ErrorListener.php';

return $this->privates['fos_rest.error_listener'] = new \Symfony\Component\HttpKernel\EventListener\ErrorListener('fos_rest.exception.twig_controller::showAction', ($this->privates['monolog.logger.request'] ?? $this->getMonolog_Logger_RequestService()), true);
