<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'fos_oauth_server.server' shared service.

if ($lazyLoad) {
    return $this->privates['fos_oauth_server.server'] = $this->createProxy('OAuth2_5885b82', function () {
        return \OAuth2_5885b82::staticProxyConstructor(function (&$wrappedInstance, \ProxyManager\Proxy\LazyLoadingInterface $proxy) {
            $wrappedInstance = $this->load('getFosOauthServer_ServerService.php', false);

            $proxy->setProxyInitializer(null);

            return true;
        });
    });
}

include_once \dirname(__DIR__, 4).'/vendor/friendsofsymfony/oauth2-php/lib/IOAuth2.php';
include_once \dirname(__DIR__, 4).'/vendor/friendsofsymfony/oauth2-php/lib/OAuth2.php';

return new \OAuth2\OAuth2(($this->privates['fos_oauth_server.storage.default'] ?? $this->load('getFosOauthServer_Storage_DefaultService.php')), []);
