<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'fos_oauth_server.storage.default' shared service.

include_once \dirname(__DIR__, 4).'/vendor/friendsofsymfony/oauth2-php/lib/IOAuth2Storage.php';
include_once \dirname(__DIR__, 4).'/vendor/friendsofsymfony/oauth2-php/lib/IOAuth2RefreshTokens.php';
include_once \dirname(__DIR__, 4).'/vendor/friendsofsymfony/oauth2-php/lib/IOAuth2GrantUser.php';
include_once \dirname(__DIR__, 4).'/vendor/friendsofsymfony/oauth2-php/lib/IOAuth2GrantCode.php';
include_once \dirname(__DIR__, 4).'/vendor/friendsofsymfony/oauth2-php/lib/IOAuth2GrantImplicit.php';
include_once \dirname(__DIR__, 4).'/vendor/friendsofsymfony/oauth2-php/lib/IOAuth2GrantClient.php';
include_once \dirname(__DIR__, 4).'/vendor/friendsofsymfony/oauth2-php/lib/IOAuth2GrantExtension.php';
include_once \dirname(__DIR__, 4).'/vendor/friendsofsymfony/oauth-server-bundle/Storage/GrantExtensionDispatcherInterface.php';
include_once \dirname(__DIR__, 4).'/vendor/friendsofsymfony/oauth-server-bundle/Storage/OAuthStorage.php';

return $this->privates['fos_oauth_server.storage.default'] = new \FOS\OAuthServerBundle\Storage\OAuthStorage(($this->services['sylius.oauth_server.client_manager'] ?? $this->load('getSylius_OauthServer_ClientManagerService.php')), ($this->privates['fos_oauth_server.access_token_manager.default'] ?? $this->load('getFosOauthServer_AccessTokenManager_DefaultService.php')), ($this->privates['fos_oauth_server.refresh_token_manager.default'] ?? $this->load('getFosOauthServer_RefreshTokenManager_DefaultService.php')), ($this->privates['fos_oauth_server.auth_code_manager.default'] ?? $this->load('getFosOauthServer_AuthCodeManager_DefaultService.php')), ($this->privates['sylius.admin_user_provider.email_or_name_based'] ?? $this->load('getSylius_AdminUserProvider_EmailOrNameBasedService.php')), ($this->privates['security.encoder_factory.generic'] ?? $this->load('getSecurity_EncoderFactory_GenericService.php')));
