<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'fos_ck_editor.installer' shared service.

include_once \dirname(__DIR__, 4).'/vendor/friendsofsymfony/ckeditor-bundle/src/Installer/CKEditorInstaller.php';

return $this->privates['fos_ck_editor.installer'] = new \FOS\CKEditorBundle\Installer\CKEditorInstaller();
