<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'gaufrette.sylius_image_adapter' shared service.

include_once \dirname(__DIR__, 4).'/vendor/knplabs/gaufrette/src/Gaufrette/Adapter.php';
include_once \dirname(__DIR__, 4).'/vendor/knplabs/gaufrette/src/Gaufrette/Adapter/StreamFactory.php';
include_once \dirname(__DIR__, 4).'/vendor/knplabs/gaufrette/src/Gaufrette/Adapter/ChecksumCalculator.php';
include_once \dirname(__DIR__, 4).'/vendor/knplabs/gaufrette/src/Gaufrette/Adapter/SizeCalculator.php';
include_once \dirname(__DIR__, 4).'/vendor/knplabs/gaufrette/src/Gaufrette/Adapter/MimeTypeProvider.php';
include_once \dirname(__DIR__, 4).'/vendor/knplabs/gaufrette/src/Gaufrette/Adapter/Local.php';

return $this->privates['gaufrette.sylius_image_adapter'] = new \Gaufrette\Adapter\Local((\dirname(__DIR__, 4).'/public/media/image'), true);
