<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'knp_gaufrette.filesystem_map' shared service.

include_once \dirname(__DIR__, 4).'/vendor/knplabs/gaufrette/src/Gaufrette/FilesystemMapInterface.php';
include_once \dirname(__DIR__, 4).'/vendor/knplabs/knp-gaufrette-bundle/FilesystemMap.php';

return $this->services['knp_gaufrette.filesystem_map'] = new \Knp\Bundle\GaufretteBundle\FilesystemMap(['sylius_image' => ($this->services['gaufrette.sylius_image_filesystem'] ?? $this->load('getGaufrette_SyliusImageFilesystemService.php'))]);
