<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'payum.http_request_verifier_builder' shared service.

include_once \dirname(__DIR__, 4).'/vendor/payum/payum/src/Payum/Core/Bridge/Symfony/Builder/HttpRequestVerifierBuilder.php';

return $this->privates['payum.http_request_verifier_builder'] = new \Payum\Core\Bridge\Symfony\Builder\HttpRequestVerifierBuilder();
