<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sylius.behat.context.setup.order' shared service.

include_once \dirname(__DIR__, 4).'/vendor/behat/behat/src/Behat/Behat/Context/Context.php';
include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Behat/Context/Setup/OrderContext.php';
include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Behat/Service/SharedStorageInterface.php';
include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Behat/Service/SharedStorage.php';

return $this->services['sylius.behat.context.setup.order'] = new \Sylius\Behat\Context\Setup\OrderContext(($this->privates['sylius.behat.shared_storage'] ?? ($this->privates['sylius.behat.shared_storage'] = new \Sylius\Behat\Service\SharedStorage())), ($this->services['sylius.factory.order'] ?? ($this->services['sylius.factory.order'] = new \Sylius\Component\Resource\Factory\Factory('App\\Entity\\Order\\Order'))), ($this->services['sylius.factory.address'] ?? $this->load('getSylius_Factory_AddressService.php')), ($this->services['sylius.factory.customer'] ?? ($this->services['sylius.factory.customer'] = new \Sylius\Component\Resource\Factory\Factory('App\\Entity\\Customer\\Customer'))), ($this->services['sylius.factory.cart_item'] ?? $this->load('getSylius_Factory_CartItemService.php')), ($this->services['sm.factory'] ?? $this->getSm_FactoryService()), ($this->services['sylius.repository.country'] ?? $this->load('getSylius_Repository_CountryService.php')), ($this->services['sylius.repository.customer'] ?? $this->load('getSylius_Repository_CustomerService.php')), ($this->services['sylius.repository.order'] ?? $this->getSylius_Repository_OrderService()), ($this->services['sylius.repository.payment_method'] ?? $this->getSylius_Repository_PaymentMethodService()), ($this->services['sylius.repository.shipping_method'] ?? $this->getSylius_Repository_ShippingMethodService()), ($this->services['sylius.product_variant_resolver.default'] ?? ($this->services['sylius.product_variant_resolver.default'] = new \Sylius\Component\Product\Resolver\DefaultProductVariantResolver())), ($this->services['sylius.order_item_quantity_modifier.limiting'] ?? $this->load('getSylius_OrderItemQuantityModifier_LimitingService.php')), ($this->services['doctrine.orm.default_entity_manager'] ?? $this->getDoctrine_Orm_DefaultEntityManagerService()));
