<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sylius.theme.templating.cache.clearer' shared service.

include_once \dirname(__DIR__, 4).'/vendor/symfony/http-kernel/CacheClearer/CacheClearerInterface.php';
include_once \dirname(__DIR__, 4).'/vendor/sylius/theme-bundle/src/Templating/Cache/Clearer/TemplatePathsCacheClearer.php';

return $this->privates['sylius.theme.templating.cache.clearer'] = new \Sylius\Bundle\ThemeBundle\Templating\Cache\Clearer\TemplatePathsCacheClearer(($this->services['sylius.theme.templating.cache'] ?? ($this->services['sylius.theme.templating.cache'] = new \Doctrine\Common\Cache\ArrayCache())));
