<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sylius.behat.context.ui.admin.managing_product_options' shared service.

include_once \dirname(__DIR__, 4).'/vendor/behat/behat/src/Behat/Behat/Context/Context.php';
include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Behat/Context/Ui/Admin/ManagingProductOptionsContext.php';

return $this->services['sylius.behat.context.ui.admin.managing_product_options'] = new \Sylius\Behat\Context\Ui\Admin\ManagingProductOptionsContext(($this->privates['sylius.behat.page.admin.product_option.index'] ?? $this->load('getSylius_Behat_Page_Admin_ProductOption_IndexService.php')), ($this->privates['sylius.behat.page.admin.product_option.create'] ?? $this->load('getSylius_Behat_Page_Admin_ProductOption_CreateService.php')), ($this->privates['sylius.behat.page.admin.product_option.update'] ?? $this->load('getSylius_Behat_Page_Admin_ProductOption_UpdateService.php')), ($this->privates['sylius.behat.current_page_resolver'] ?? $this->load('getSylius_Behat_CurrentPageResolverService.php')));
