<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sylius.behat.context.setup.customer' shared service.

include_once \dirname(__DIR__, 4).'/vendor/behat/behat/src/Behat/Behat/Context/Context.php';
include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Behat/Context/Setup/CustomerContext.php';
include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Behat/Service/SharedStorageInterface.php';
include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Behat/Service/SharedStorage.php';

return $this->services['sylius.behat.context.setup.customer'] = new \Sylius\Behat\Context\Setup\CustomerContext(($this->privates['sylius.behat.shared_storage'] ?? ($this->privates['sylius.behat.shared_storage'] = new \Sylius\Behat\Service\SharedStorage())), ($this->services['sylius.repository.customer'] ?? $this->load('getSylius_Repository_CustomerService.php')), ($this->services['doctrine.orm.default_entity_manager'] ?? $this->getDoctrine_Orm_DefaultEntityManagerService()), ($this->services['sylius.factory.customer'] ?? ($this->services['sylius.factory.customer'] = new \Sylius\Component\Resource\Factory\Factory('App\\Entity\\Customer\\Customer'))), ($this->services['sylius.factory.shop_user'] ?? $this->load('getSylius_Factory_ShopUserService.php')), ($this->services['sylius.factory.address'] ?? $this->load('getSylius_Factory_AddressService.php')));
