<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sylius.behat.context.ui.admin.managing_orders' shared service.

include_once \dirname(__DIR__, 4).'/vendor/behat/behat/src/Behat/Behat/Context/Context.php';
include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Behat/Context/Ui/Admin/ManagingOrdersContext.php';
include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Behat/Service/SharedStorageInterface.php';
include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Behat/Service/SharedStorage.php';

return $this->services['sylius.behat.context.ui.admin.managing_orders'] = new \Sylius\Behat\Context\Ui\Admin\ManagingOrdersContext(($this->privates['sylius.behat.shared_storage'] ?? ($this->privates['sylius.behat.shared_storage'] = new \Sylius\Behat\Service\SharedStorage())), ($this->privates['sylius.behat.page.admin.order.index'] ?? $this->load('getSylius_Behat_Page_Admin_Order_IndexService.php')), ($this->privates['sylius.behat.page.admin.order.show'] ?? $this->load('getSylius_Behat_Page_Admin_Order_ShowService.php')), ($this->privates['sylius.behat.page.admin.order.update'] ?? $this->load('getSylius_Behat_Page_Admin_Order_UpdateService.php')), ($this->privates['sylius.behat.page.admin.order.history'] ?? $this->load('getSylius_Behat_Page_Admin_Order_HistoryService.php')), ($this->privates['sylius.behat.notification_checker'] ?? $this->load('getSylius_Behat_NotificationCheckerService.php')), ($this->privates['sylius.behat.shared_security'] ?? $this->load('getSylius_Behat_SharedSecurityService.php')));
