<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sylius.custom_factory.promotion_action.inner' shared service.

return $this->privates['sylius.custom_factory.promotion_action.inner'] = new \Sylius\Component\Resource\Factory\Factory('App\\Entity\\Promotion\\PromotionAction');
