<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sylius.behat.context.transform.address' shared service.

include_once \dirname(__DIR__, 4).'/vendor/behat/behat/src/Behat/Behat/Context/Context.php';
include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Behat/Context/Transform/AddressContext.php';
include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Component/Addressing/Converter/CountryNameConverterInterface.php';
include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Component/Addressing/Converter/CountryNameConverter.php';

return $this->services['sylius.behat.context.transform.address'] = new \Sylius\Behat\Context\Transform\AddressContext(($this->services['sylius.factory.address'] ?? $this->load('getSylius_Factory_AddressService.php')), ($this->services['sylius.converter.country_name'] ?? ($this->services['sylius.converter.country_name'] = new \Sylius\Component\Addressing\Converter\CountryNameConverter())), ($this->services['sylius.repository.address'] ?? $this->load('getSylius_Repository_AddressService.php')), ($this->services['sylius.fixture.example_factory.address'] ?? $this->load('getSylius_Fixture_ExampleFactory_AddressService.php')));
