<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sylius.behat.context.ui.admin.managing_products' shared service.

include_once \dirname(__DIR__, 4).'/vendor/behat/behat/src/Behat/Behat/Context/Context.php';
include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Behat/Context/Ui/Admin/ManagingProductsContext.php';
include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Behat/Service/SharedStorageInterface.php';
include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Behat/Service/SharedStorage.php';

return $this->services['sylius.behat.context.ui.admin.managing_products'] = new \Sylius\Behat\Context\Ui\Admin\ManagingProductsContext(($this->privates['sylius.behat.shared_storage'] ?? ($this->privates['sylius.behat.shared_storage'] = new \Sylius\Behat\Service\SharedStorage())), ($this->privates['sylius.behat.page.admin.product.create_simple'] ?? $this->load('getSylius_Behat_Page_Admin_Product_CreateSimpleService.php')), ($this->privates['sylius.behat.page.admin.product.create_configurable'] ?? $this->load('getSylius_Behat_Page_Admin_Product_CreateConfigurableService.php')), ($this->privates['sylius.behat.page.admin.product.index'] ?? $this->load('getSylius_Behat_Page_Admin_Product_IndexService.php')), ($this->privates['sylius.behat.page.admin.product.update_simple'] ?? $this->load('getSylius_Behat_Page_Admin_Product_UpdateSimpleService.php')), ($this->privates['sylius.behat.page.admin.product.update_configurable'] ?? $this->load('getSylius_Behat_Page_Admin_Product_UpdateConfigurableService.php')), ($this->privates['sylius.behat.page.admin.product_review.index'] ?? $this->load('getSylius_Behat_Page_Admin_ProductReview_IndexService.php')), ($this->privates['sylius.behat.page.admin.product.index_per_taxon'] ?? $this->load('getSylius_Behat_Page_Admin_Product_IndexPerTaxonService.php')), ($this->privates['sylius.behat.page.admin.product_variant.create'] ?? $this->load('getSylius_Behat_Page_Admin_ProductVariant_CreateService.php')), ($this->privates['sylius.behat.page.admin.product_variant.generate'] ?? $this->load('getSylius_Behat_Page_Admin_ProductVariant_GenerateService.php')), ($this->privates['sylius.behat.current_page_resolver'] ?? $this->load('getSylius_Behat_CurrentPageResolverService.php')), ($this->privates['sylius.behat.notification_checker'] ?? $this->load('getSylius_Behat_NotificationCheckerService.php')));
