<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sylius.behat.context.ui.shop.checkout' shared service.

include_once \dirname(__DIR__, 4).'/vendor/behat/behat/src/Behat/Behat/Context/Context.php';
include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Behat/Context/Ui/Shop/CheckoutContext.php';

return $this->services['sylius.behat.context.ui.shop.checkout'] = new \Sylius\Behat\Context\Ui\Shop\CheckoutContext(($this->privates['sylius.behat.page.shop.checkout.address'] ?? $this->load('getSylius_Behat_Page_Shop_Checkout_AddressService.php')), ($this->privates['sylius.behat.page.shop.checkout.select_payment'] ?? $this->load('getSylius_Behat_Page_Shop_Checkout_SelectPaymentService.php')), ($this->privates['sylius.behat.page.shop.checkout.select_shipping'] ?? $this->load('getSylius_Behat_Page_Shop_Checkout_SelectShippingService.php')), ($this->privates['sylius.behat.page.shop.checkout.complete'] ?? $this->load('getSylius_Behat_Page_Shop_Checkout_CompleteService.php')), ($this->privates['sylius.behat.page.shop.account.register'] ?? $this->load('getSylius_Behat_Page_Shop_Account_RegisterService.php')), ($this->privates['sylius.behat.element.shop.account.register'] ?? $this->load('getSylius_Behat_Element_Shop_Account_RegisterService.php')), ($this->privates['sylius.behat.current_page_resolver'] ?? $this->load('getSylius_Behat_CurrentPageResolverService.php')), ($this->services['sylius.behat.context.ui.shop.checkout.addressing'] ?? $this->load('getSylius_Behat_Context_Ui_Shop_Checkout_AddressingService.php')), ($this->services['sylius.behat.context.ui.shop.checkout.shipping'] ?? $this->load('getSylius_Behat_Context_Ui_Shop_Checkout_ShippingService.php')), ($this->services['sylius.behat.context.ui.shop.checkout.payment'] ?? $this->load('getSylius_Behat_Context_Ui_Shop_Checkout_PaymentService.php')));
