<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sylius.behat.context.ui.shop.checkout.order_details' shared service.

include_once \dirname(__DIR__, 4).'/vendor/behat/behat/src/Behat/Behat/Context/Context.php';
include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Behat/Context/Ui/Shop/Checkout/CheckoutOrderDetailsContext.php';

return $this->services['sylius.behat.context.ui.shop.checkout.order_details'] = new \Sylius\Behat\Context\Ui\Shop\Checkout\CheckoutOrderDetailsContext(($this->privates['sylius.behat.page.shop.order.show'] ?? $this->load('getSylius_Behat_Page_Shop_Order_ShowService.php')));
