<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sylius.behat.context.ui.admin.managing_administrators' shared service.

include_once \dirname(__DIR__, 4).'/vendor/behat/behat/src/Behat/Behat/Context/Context.php';
include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Behat/Context/Ui/Admin/ManagingAdministratorsContext.php';
include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Behat/Service/SharedStorageInterface.php';
include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Behat/Service/SharedStorage.php';

return $this->services['sylius.behat.context.ui.admin.managing_administrators'] = new \Sylius\Behat\Context\Ui\Admin\ManagingAdministratorsContext(($this->privates['sylius.behat.page.admin.administrator.create'] ?? $this->load('getSylius_Behat_Page_Admin_Administrator_CreateService.php')), ($this->privates['sylius.behat.page.admin.administrator.index'] ?? $this->load('getSylius_Behat_Page_Admin_Administrator_IndexService.php')), ($this->privates['sylius.behat.page.admin.administrator.update'] ?? $this->load('getSylius_Behat_Page_Admin_Administrator_UpdateService.php')), ($this->privates['sylius.behat.element.admin.top_bar'] ?? $this->load('getSylius_Behat_Element_Admin_TopBarService.php')), ($this->privates['sylius.behat.notification_checker'] ?? $this->load('getSylius_Behat_NotificationCheckerService.php')), ($this->services['sylius.repository.admin_user'] ?? $this->load('getSylius_Repository_AdminUserService.php')), ($this->privates['sylius.behat.shared_storage'] ?? ($this->privates['sylius.behat.shared_storage'] = new \Sylius\Behat\Service\SharedStorage())));
