<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sylius.test.factory.promotion' shared service.

include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Component/Core/Test/Factory/TestPromotionFactoryInterface.php';
include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Component/Core/Test/Factory/TestPromotionFactory.php';

return $this->services['sylius.test.factory.promotion'] = new \Sylius\Component\Core\Test\Factory\TestPromotionFactory(($this->services['sylius.factory.promotion'] ?? ($this->services['sylius.factory.promotion'] = new \Sylius\Component\Resource\Factory\Factory('App\\Entity\\Promotion\\Promotion'))));
