<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sylius.behat.context.ui.admin.browsing_product_variants' shared service.

include_once \dirname(__DIR__, 4).'/vendor/behat/behat/src/Behat/Behat/Context/Context.php';
include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Behat/Context/Ui/Admin/BrowsingProductVariantsContext.php';

return $this->services['sylius.behat.context.ui.admin.browsing_product_variants'] = new \Sylius\Behat\Context\Ui\Admin\BrowsingProductVariantsContext(($this->privates['sylius.behat.page.admin.product_variant.index'] ?? $this->load('getSylius_Behat_Page_Admin_ProductVariant_IndexService.php')), ($this->services['sylius.product_variant_resolver.default'] ?? ($this->services['sylius.product_variant_resolver.default'] = new \Sylius\Component\Product\Resolver\DefaultProductVariantResolver())));
