<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sylius.behat.context.transform.province' shared service.

include_once \dirname(__DIR__, 4).'/vendor/behat/behat/src/Behat/Behat/Context/Context.php';
include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Behat/Context/Transform/ProvinceContext.php';

return $this->services['sylius.behat.context.transform.province'] = new \Sylius\Behat\Context\Transform\ProvinceContext(($this->services['sylius.repository.province'] ?? $this->getSylius_Repository_ProvinceService()));
