<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sylius.routing.loader.resource' shared service.

include_once \dirname(__DIR__, 4).'/vendor/symfony/config/Loader/LoaderInterface.php';
include_once \dirname(__DIR__, 4).'/vendor/sylius/resource-bundle/src/Bundle/Routing/ResourceLoader.php';
include_once \dirname(__DIR__, 4).'/vendor/sylius/resource-bundle/src/Bundle/Routing/RouteFactoryInterface.php';
include_once \dirname(__DIR__, 4).'/vendor/sylius/resource-bundle/src/Bundle/Routing/RouteFactory.php';

return $this->privates['sylius.routing.loader.resource'] = new \Sylius\Bundle\ResourceBundle\Routing\ResourceLoader(($this->privates['sylius.resource_registry'] ?? $this->getSylius_ResourceRegistryService()), new \Sylius\Bundle\ResourceBundle\Routing\RouteFactory());
