<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sylius.fixture.example_factory.product_association_type' shared service.

include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/CoreBundle/Fixture/Factory/ExampleFactoryInterface.php';
include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/CoreBundle/Fixture/Factory/AbstractExampleFactory.php';
include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/CoreBundle/Fixture/Factory/ProductAssociationTypeExampleFactory.php';

return $this->services['sylius.fixture.example_factory.product_association_type'] = new \Sylius\Bundle\CoreBundle\Fixture\Factory\ProductAssociationTypeExampleFactory(($this->services['sylius.factory.product_association_type'] ?? $this->load('getSylius_Factory_ProductAssociationTypeService.php')), ($this->services['sylius.repository.locale'] ?? $this->getSylius_Repository_LocaleService()));
