<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sylius.behat.context.ui.shop.account' shared service.

include_once \dirname(__DIR__, 4).'/vendor/behat/behat/src/Behat/Behat/Context/Context.php';
include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Behat/Context/Ui/Shop/AccountContext.php';

return $this->services['sylius.behat.context.ui.shop.account'] = new \Sylius\Behat\Context\Ui\Shop\AccountContext(($this->privates['sylius.behat.page.shop.account.dashboard'] ?? $this->load('getSylius_Behat_Page_Shop_Account_DashboardService.php')), ($this->privates['sylius.behat.page.shop.account.profile_update'] ?? $this->load('getSylius_Behat_Page_Shop_Account_ProfileUpdateService.php')), ($this->privates['sylius.behat.page.shop.account.change_password'] ?? $this->load('getSylius_Behat_Page_Shop_Account_ChangePasswordService.php')), ($this->privates['sylius.behat.page.shop.account.order.index'] ?? $this->load('getSylius_Behat_Page_Shop_Account_Order_IndexService.php')), ($this->privates['sylius.behat.page.shop.account.order.show'] ?? $this->load('getSylius_Behat_Page_Shop_Account_Order_ShowService.php')), ($this->privates['sylius.behat.page.shop.account.login'] ?? $this->load('getSylius_Behat_Page_Shop_Account_LoginService.php')), ($this->privates['sylius.behat.notification_checker'] ?? $this->load('getSylius_Behat_NotificationCheckerService.php')));
