<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sylius.form.type.user_request_password_reset' shared service.

include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
include_once \dirname(__DIR__, 4).'/vendor/sylius/resource-bundle/src/Bundle/Form/Type/AbstractResourceType.php';
include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/UserBundle/Form/Type/UserRequestPasswordResetType.php';

return $this->services['sylius.form.type.user_request_password_reset'] = new \Sylius\Bundle\UserBundle\Form\Type\UserRequestPasswordResetType('Sylius\\Bundle\\UserBundle\\Form\\Model\\PasswordResetRequest', $this->parameters['sylius.form.type.user_request_password_reset.validation_groups']);
