<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sylius.form.type.resource_autocomplete_choice' shared service.

include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
include_once \dirname(__DIR__, 4).'/vendor/sylius/resource-bundle/src/Bundle/Form/Type/ResourceAutocompleteChoiceType.php';

return $this->services['sylius.form.type.resource_autocomplete_choice'] = new \Sylius\Bundle\ResourceBundle\Form\Type\ResourceAutocompleteChoiceType(($this->privates['sylius.registry.resource_repository'] ?? $this->load('getSylius_Registry_ResourceRepositoryService.php')));
