<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sylius.behat.context.transform.customer_group' shared service.

include_once \dirname(__DIR__, 4).'/vendor/behat/behat/src/Behat/Behat/Context/Context.php';
include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Behat/Context/Transform/CustomerGroupContext.php';

return $this->services['sylius.behat.context.transform.customer_group'] = new \Sylius\Behat\Context\Transform\CustomerGroupContext(($this->services['sylius.repository.customer_group'] ?? $this->load('getSylius_Repository_CustomerGroupService.php')));
