<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sylius.behat.context.ui.shop.product' shared service.

include_once \dirname(__DIR__, 4).'/vendor/behat/behat/src/Behat/Behat/Context/Context.php';
include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Behat/Context/Ui/Shop/ProductContext.php';

return $this->services['sylius.behat.context.ui.shop.product'] = new \Sylius\Behat\Context\Ui\Shop\ProductContext(($this->privates['sylius.behat.page.shop.product.show'] ?? $this->load('getSylius_Behat_Page_Shop_Product_ShowService.php')), ($this->privates['sylius.behat.page.shop.product.index'] ?? $this->load('getSylius_Behat_Page_Shop_Product_IndexService.php')), ($this->privates['sylius.behat.page.shop.product_reviews.index'] ?? $this->load('getSylius_Behat_Page_Shop_ProductReviews_IndexService.php')), ($this->privates['sylius.behat.page.error'] ?? $this->load('getSylius_Behat_Page_ErrorService.php')));
