<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sylius.behat.context.api.admin.managing_taxons' shared service.

include_once \dirname(__DIR__, 4).'/vendor/behat/behat/src/Behat/Behat/Context/Context.php';
include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Behat/Context/Api/Admin/ManagingTaxonsContext.php';

return $this->services['sylius.behat.context.api.admin.managing_taxons'] = new \Sylius\Behat\Context\Api\Admin\ManagingTaxonsContext((isset($this->factories['test.client']) ? $this->factories['test.client']() : $this->load('getTest_ClientService.php')), ($this->services['session'] ?? $this->getSessionService()));
