<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sylius.behat.context.ui.admin.managing_locales' shared service.

include_once \dirname(__DIR__, 4).'/vendor/behat/behat/src/Behat/Behat/Context/Context.php';
include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Behat/Context/Ui/Admin/ManagingLocalesContext.php';

return $this->services['sylius.behat.context.ui.admin.managing_locales'] = new \Sylius\Behat\Context\Ui\Admin\ManagingLocalesContext(($this->privates['sylius.behat.page.admin.locale.create'] ?? $this->load('getSylius_Behat_Page_Admin_Locale_CreateService.php')), ($this->privates['sylius.behat.page.admin.locale.index'] ?? $this->load('getSylius_Behat_Page_Admin_Locale_IndexService.php')));
