<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sylius.behat.context.setup.product_option' shared service.

include_once \dirname(__DIR__, 4).'/vendor/behat/behat/src/Behat/Behat/Context/Context.php';
include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Behat/Context/Setup/ProductOptionContext.php';
include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Behat/Service/SharedStorageInterface.php';
include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Behat/Service/SharedStorage.php';

return $this->services['sylius.behat.context.setup.product_option'] = new \Sylius\Behat\Context\Setup\ProductOptionContext(($this->privates['sylius.behat.shared_storage'] ?? ($this->privates['sylius.behat.shared_storage'] = new \Sylius\Behat\Service\SharedStorage())), ($this->services['sylius.repository.product_option'] ?? $this->load('getSylius_Repository_ProductOptionService.php')), ($this->services['sylius.factory.product_option'] ?? $this->load('getSylius_Factory_ProductOptionService.php')), ($this->services['sylius.factory.product_option_value'] ?? $this->load('getSylius_Factory_ProductOptionValueService.php')), ($this->services['doctrine.orm.default_entity_manager'] ?? $this->getDoctrine_Orm_DefaultEntityManagerService()));
