<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Sylius\Component\Taxonomy\Factory\TaxonFactoryInterface' shared service.

include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Component/Taxonomy/Factory/TaxonFactoryInterface.php';
include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Component/Taxonomy/Factory/TaxonFactory.php';

return $this->services['Sylius\\Component\\Taxonomy\\Factory\\TaxonFactoryInterface'] = new \Sylius\Component\Taxonomy\Factory\TaxonFactory(($this->privates['sylius.custom_factory.taxon.inner'] ?? $this->load('getSylius_CustomFactory_Taxon_InnerService.php')));
