# .smyfony.cloud.yaml
name: 'tartare'

type: 'php:7.4'

build:
    flavor: 'none'

size: AUTO

disk: 1070

mounts:
    '/public/assets': { source: local, source_path: assets }
    '/public/bundles': { source: local, source_path: bundles }
    '/public/media': { source: local, source_path: media }
    '/public/upload': { source: local, source_path: upload }

web:
    locations:
        "/":
            root: "public"
            passthru: "/index.php"
            index:
                - index.php
            expires: -1
            scripts: true
            allow: true
            rules:
                '\.(gif|jpe?g|png)$':
                    expires: 60
        "/admin":
            expires: 300
            passthru: true
            allow: true

        "/assets/shop":
            expires: 2w
            passthru: false
            allow: false
            rules:
                # Only allow static files from the assets directories.
                '\.(css|js|jpe?g|png|gif|svgz?|ico|bmp|tiff?|wbmp|ico|jng|bmp|html|pdf|otf|woff2|woff|eot|ttf|jar|swf|ogx|avi|wmv|asf|asx|mng|flv|webm|mov|ogv|mpe|mpe?g|mp4|3gpp|weba|ra|m4a|mp3|mp2|mpe?ga|midi?)$':
                    allow: true
        "/media/image":
            expires: 2w
            passthru: false
            allow: false
            rules:
                # Only allow static files from the assets directories.
                '\.(jpe?g|png|gif|svgz?)$':
                    allow: true

dependancies:
    php:
        symfony/console: '*'
        sylius/sylius: "~1.7.0"
        symfony/dotenv: "^4.4"
    nodejs:
        yarn: '1.22.4'

hooks:
    build: |
        set -x -e

        curl -s https://get.symfony.com/cloud/configurator | (>&2 bash)
        (>&2
            symfony-build
        )
        (>&2
            # Setup everything to use the Node installation
            unset NPM_CONFIG_PREFIX
            export NVM_DIR=${SYMFONY_APP_DIR}/.nvm
            set +x && . "${NVM_DIR}/nvm.sh" use --lts && set -x
            # Starting from here, everything is setup to use the same Node
            yarn encore dev
        )
        ( mkdir var/cache/dev
        )

crons:
    cleanup_cart:
        spec: '0 */6 * * *'
        cmd: croncape /usr/bin/flock -n /tmp/lock.app.cleanup_cart symfony console sylius:remove-expired-carts --verbose
    cleanup_order:
        spec: '0 */6 * * *'
        cmd: croncape /usr/bin/flock -n /tmp/lock.app.cleanup_order symfony console sylius:cancel-unpaid-orders --verbose

