# .smyfony.cloud.yaml
name: 'acme'

type: 'php:7.4'

build:
    flavor: 'none'

size: AUTO

disk: 5070

mounts:
    '/public/assets': { source: local, source_path: assets }
    '/public/bundles': { source: local, source_path: bundles }
    '/public/media': { source: local, source_path: media }
    '/public/upload': { source: local, source_path: upload }

dependancies:
    php:
        symfony/console: '*'
        redis: "6.0.6"
        tokenizer: "3.1"
        ctype: "1.18"
        symfony/intl: "4.4.10"
        symfony/amqp-pack: "1.0.11"
        libsodium: "1.0.18_1"
        sylius/sylius: "~1.7.0"
        symfony/dotenv: "^4.4"
        symfony/flex: "^1.2"  
    nodejs:
        yarn: '1.22.4'

hooks:
    build: |
        set -x -e

        curl -s https://get.symfony.com/cloud/configurator | (>&2 bash)
        (>&2
            symfony-build
        )
        (>&2
            # Setup everything to use the Node installation
            unset NPM_CONFIG_PREFIX
            export NVM_DIR=${SYMFONY_APP_DIR}/.nvm
            set +x && . "${NVM_DIR}/nvm.sh" use --lts && set -x
            # Starting from here, everything is setup to use the same Node
            yarn encore dev
        )

crons:
    cleanup_cart:
        spec: '0 */6 * * *'
        cmd: croncape /usr/bin/flock -n /tmp/lock.app.cleanup_cart symfony console sylius:remove-expired-carts --verbose
    cleanup_order:
        spec: '0 */6 * * *'
        cmd: croncape /usr/bin/flock -n /tmp/lock.app.cleanup_order symfony console sylius:cancel-unpaid-orders --verbose

