<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Sylius\Bundle\AdminBundle\Twig\ChannelNameExtension' shared service.

include_once \dirname(__DIR__, 4).'/vendor/twig/twig/src/Extension/ExtensionInterface.php';
include_once \dirname(__DIR__, 4).'/vendor/twig/twig/src/Extension/AbstractExtension.php';
include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/AdminBundle/Twig/ChannelNameExtension.php';

return $this->services['Sylius\\Bundle\\AdminBundle\\Twig\\ChannelNameExtension'] = new \Sylius\Bundle\AdminBundle\Twig\ChannelNameExtension(($this->services['sylius.repository.channel'] ?? $this->getSylius_Repository_ChannelService()));
