<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'fos_rest.serializer.flatten_exception_handler' shared service.

include_once \dirname(__DIR__, 4).'/vendor/jms/serializer/src/JMS/Serializer/Handler/SubscribingHandlerInterface.php';
include_once \dirname(__DIR__, 4).'/vendor/friendsofsymfony/rest-bundle/Serializer/Normalizer/FlattenExceptionHandler.php';
include_once \dirname(__DIR__, 4).'/vendor/friendsofsymfony/rest-bundle/Util/ExceptionValueMap.php';

return $this->privates['fos_rest.serializer.flatten_exception_handler'] = new \FOS\RestBundle\Serializer\Normalizer\FlattenExceptionHandler(($this->privates['fos_rest.exception.codes_map'] ?? ($this->privates['fos_rest.exception.codes_map'] = new \FOS\RestBundle\Util\ExceptionValueMap([]))), ($this->privates['fos_rest.exception.messages_map'] ?? ($this->privates['fos_rest.exception.messages_map'] = new \FOS\RestBundle\Util\ExceptionValueMap([]))), false, false);
