<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'knp_gaufrette.command.filesystem_keys' shared service.

include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
include_once \dirname(__DIR__, 4).'/vendor/knplabs/knp-gaufrette-bundle/Command/FilesystemKeysCommand.php';

$this->privates['knp_gaufrette.command.filesystem_keys'] = $instance = new \Knp\Bundle\GaufretteBundle\Command\FilesystemKeysCommand(($this->services['knp_gaufrette.filesystem_map'] ?? $this->load('getKnpGaufrette_FilesystemMapService.php')));

$instance->setName('gaufrette:filesystem:keys');

return $instance;
