<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sonata.block.service.menu' shared service.

include_once \dirname(__DIR__, 4).'/vendor/sonata-project/block-bundle/src/Block/Service/BlockServiceInterface.php';
include_once \dirname(__DIR__, 4).'/vendor/sonata-project/block-bundle/src/Block/Service/AbstractBlockService.php';
include_once \dirname(__DIR__, 4).'/vendor/sonata-project/block-bundle/src/Block/Service/EditableBlockService.php';
include_once \dirname(__DIR__, 4).'/vendor/sonata-project/block-bundle/src/Block/Service/MenuBlockService.php';
include_once \dirname(__DIR__, 4).'/vendor/sonata-project/block-bundle/src/Menu/MenuRegistryInterface.php';
include_once \dirname(__DIR__, 4).'/vendor/sonata-project/block-bundle/src/Menu/MenuRegistry.php';

return $this->services['sonata.block.service.menu'] = new \Sonata\BlockBundle\Block\Service\MenuBlockService(($this->services['twig'] ?? $this->load('getTwigService.php')), ($this->privates['knp_menu.menu_provider.chain'] ?? $this->load('getKnpMenu_MenuProvider_ChainService.php')), ($this->services['sonata.block.menu.registry'] ?? ($this->services['sonata.block.menu.registry'] = new \Sonata\BlockBundle\Menu\MenuRegistry(''))));
