<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sylius.fixture.example_factory.channel' shared service.

include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/CoreBundle/Fixture/Factory/ExampleFactoryInterface.php';
include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/CoreBundle/Fixture/Factory/AbstractExampleFactory.php';
include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/CoreBundle/Fixture/Factory/ChannelExampleFactory.php';

return $this->services['sylius.fixture.example_factory.channel'] = new \Sylius\Bundle\CoreBundle\Fixture\Factory\ChannelExampleFactory(($this->services['Sylius\\Component\\Channel\\Factory\\ChannelFactoryInterface'] ?? $this->load('getChannelFactoryInterfaceService.php')), ($this->services['sylius.repository.locale'] ?? $this->getSylius_Repository_LocaleService()), ($this->services['sylius.repository.currency'] ?? $this->load('getSylius_Repository_CurrencyService.php')), ($this->services['sylius.repository.zone'] ?? $this->load('getSylius_Repository_ZoneService.php')));
