<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sylius_fixtures.suite_loader' shared service.

include_once \dirname(__DIR__, 4).'/vendor/sylius/fixtures-bundle/src/Loader/SuiteLoaderInterface.php';
include_once \dirname(__DIR__, 4).'/vendor/sylius/fixtures-bundle/src/Loader/HookableSuiteLoader.php';
include_once \dirname(__DIR__, 4).'/vendor/sylius/fixtures-bundle/src/Loader/SuiteLoader.php';

return $this->services['sylius_fixtures.suite_loader'] = new \Sylius\Bundle\FixturesBundle\Loader\HookableSuiteLoader(new \Sylius\Bundle\FixturesBundle\Loader\SuiteLoader(($this->services['sylius_fixtures.fixture_loader'] ?? $this->load('getSyliusFixtures_FixtureLoaderService.php'))));
