<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sylius.form.extension.type.api_order_item' shared service.

include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/AdminApiBundle/Form/Type/OrderItemType.php';

return $this->services['sylius.form.extension.type.api_order_item'] = new \Sylius\Bundle\AdminApiBundle\Form\Type\OrderItemType(($this->services['sylius.repository.product_variant'] ?? $this->load('getSylius_Repository_ProductVariantService.php')));
