<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sylius.theme.templating.file_locator' shared service.

include_once \dirname(__DIR__, 4).'/vendor/symfony/config/FileLocatorInterface.php';
include_once \dirname(__DIR__, 4).'/vendor/sylius/theme-bundle/src/Templating/Locator/TemplateFileLocator.php';

return $this->privates['sylius.theme.templating.file_locator'] = new \Sylius\Bundle\ThemeBundle\Templating\Locator\TemplateFileLocator(($this->privates['sylius.theme.templating.file_locator.inner'] ?? $this->load('getSylius_Theme_Templating_FileLocator_InnerService.php')), ($this->privates['sylius.theme.context.channel_based'] ?? $this->getSylius_Theme_Context_ChannelBasedService()), ($this->services['Sylius\\Bundle\\ThemeBundle\\HierarchyProvider\\ThemeHierarchyProviderInterface'] ?? ($this->services['Sylius\\Bundle\\ThemeBundle\\HierarchyProvider\\ThemeHierarchyProviderInterface'] = new \Sylius\Bundle\ThemeBundle\HierarchyProvider\ThemeHierarchyProvider())), ($this->services['Sylius\\Bundle\\ThemeBundle\\Templating\\Locator\\TemplateLocatorInterface'] ?? $this->load('getTemplateLocatorInterfaceService.php')), $this->targetDir.'');
