<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sylius.form.type.locale_choice' shared service.

include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/LocaleBundle/Form/Type/LocaleChoiceType.php';

return $this->services['sylius.form.type.locale_choice'] = new \Sylius\Bundle\LocaleBundle\Form\Type\LocaleChoiceType(($this->services['sylius.repository.locale'] ?? $this->getSylius_Repository_LocaleService()));
