<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sylius.grid.data_extractor.property_access' shared service.

include_once \dirname(__DIR__, 4).'/vendor/sylius/grid-bundle/src/Component/DataExtractor/DataExtractorInterface.php';
include_once \dirname(__DIR__, 4).'/vendor/sylius/grid-bundle/src/Component/DataExtractor/PropertyAccessDataExtractor.php';

return $this->services['sylius.grid.data_extractor.property_access'] = new \Sylius\Component\Grid\DataExtractor\PropertyAccessDataExtractor(($this->privates['property_accessor'] ?? $this->load('getPropertyAccessorService.php')));
