<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'twig' shared service.

include_once \dirname(__DIR__, 4).'/vendor/twig/twig/src/Environment.php';
include_once \dirname(__DIR__, 4).'/vendor/twig/twig/src/Loader/LoaderInterface.php';
include_once \dirname(__DIR__, 4).'/vendor/twig/twig/src/Loader/ExistsLoaderInterface.php';
include_once \dirname(__DIR__, 4).'/vendor/sylius/theme-bundle/src/Twig/ThemeFilesystemLoader.php';
include_once \dirname(__DIR__, 4).'/vendor/twig/twig/src/Loader/SourceContextLoaderInterface.php';
include_once \dirname(__DIR__, 4).'/vendor/twig/twig/src/Loader/FilesystemLoader.php';
include_once \dirname(__DIR__, 4).'/vendor/symfony/twig-bundle/Loader/FilesystemLoader.php';
include_once \dirname(__DIR__, 4).'/vendor/twig/twig/src/Extension/ExtensionInterface.php';
include_once \dirname(__DIR__, 4).'/vendor/twig/twig/src/Extension/AbstractExtension.php';
include_once \dirname(__DIR__, 4).'/vendor/symfony/twig-bridge/Extension/CsrfExtension.php';
include_once \dirname(__DIR__, 4).'/vendor/symfony/twig-bridge/Extension/LogoutUrlExtension.php';
include_once \dirname(__DIR__, 4).'/vendor/symfony/twig-bridge/Extension/SecurityExtension.php';
include_once \dirname(__DIR__, 4).'/vendor/symfony/twig-bridge/Extension/TranslationExtension.php';
include_once \dirname(__DIR__, 4).'/vendor/symfony/twig-bridge/Extension/AssetExtension.php';
include_once \dirname(__DIR__, 4).'/vendor/symfony/asset/Packages.php';
include_once \dirname(__DIR__, 4).'/vendor/symfony/asset/PackageInterface.php';
include_once \dirname(__DIR__, 4).'/vendor/symfony/asset/Package.php';
include_once \dirname(__DIR__, 4).'/vendor/symfony/asset/PathPackage.php';
include_once \dirname(__DIR__, 4).'/vendor/sylius/theme-bundle/src/Asset/Package/PathPackage.php';
include_once \dirname(__DIR__, 4).'/vendor/symfony/asset/VersionStrategy/VersionStrategyInterface.php';
include_once \dirname(__DIR__, 4).'/vendor/symfony/asset/VersionStrategy/EmptyVersionStrategy.php';
include_once \dirname(__DIR__, 4).'/vendor/symfony/asset/Context/ContextInterface.php';
include_once \dirname(__DIR__, 4).'/vendor/symfony/asset/Context/RequestStackContext.php';
include_once \dirname(__DIR__, 4).'/vendor/symfony/twig-bridge/Extension/CodeExtension.php';
include_once \dirname(__DIR__, 4).'/vendor/symfony/twig-bridge/Extension/RoutingExtension.php';
include_once \dirname(__DIR__, 4).'/vendor/symfony/twig-bridge/Extension/YamlExtension.php';
include_once \dirname(__DIR__, 4).'/vendor/symfony/twig-bridge/Extension/StopwatchExtension.php';
include_once \dirname(__DIR__, 4).'/vendor/symfony/twig-bridge/Extension/ExpressionExtension.php';
include_once \dirname(__DIR__, 4).'/vendor/symfony/twig-bridge/Extension/HttpKernelExtension.php';
include_once \dirname(__DIR__, 4).'/vendor/symfony/twig-bridge/Extension/HttpFoundationExtension.php';
include_once \dirname(__DIR__, 4).'/vendor/symfony/http-foundation/UrlHelper.php';
include_once \dirname(__DIR__, 4).'/vendor/symfony/twig-bridge/Extension/FormExtension.php';
include_once \dirname(__DIR__, 4).'/vendor/twig/intl-extra/src/IntlExtension.php';
include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/MoneyBundle/Twig/ConvertMoneyExtension.php';
include_once \dirname(__DIR__, 4).'/vendor/doctrine/doctrine-bundle/Twig/DoctrineExtension.php';
include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/OrderBundle/Twig/AggregateAdjustmentsExtension.php';
include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/MoneyBundle/Twig/FormatMoneyExtension.php';
include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/CurrencyBundle/Twig/CurrencyExtension.php';
include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/LocaleBundle/Twig/LocaleExtension.php';
include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/InventoryBundle/Twig/InventoryExtension.php';
include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/UiBundle/Twig/PercentageExtension.php';
include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/UiBundle/Twig/SortByExtension.php';
include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/UiBundle/Twig/TemplateEventExtension.php';
include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/UiBundle/Renderer/TemplateEventRendererInterface.php';
include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/UiBundle/Renderer/DelegatingTemplateEventRenderer.php';
include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/UiBundle/Renderer/TemplateBlockRendererInterface.php';
include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/UiBundle/Renderer/TwigTemplateBlockRenderer.php';
include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/CoreBundle/Twig/PriceExtension.php';
include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/CoreBundle/Twig/VariantResolverExtension.php';
include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/CoreBundle/Twig/ProductVariantsPricesExtension.php';
include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/CoreBundle/Twig/CheckoutStepsExtension.php';
include_once \dirname(__DIR__, 4).'/vendor/sylius/grid-bundle/src/Bundle/Twig/GridExtension.php';
include_once \dirname(__DIR__, 4).'/vendor/sylius/grid-bundle/src/Bundle/Twig/BulkActionGridExtension.php';
include_once \dirname(__DIR__, 4).'/vendor/winzou/state-machine/src/SM/Extension/Twig/SMExtension.php';
include_once \dirname(__DIR__, 4).'/vendor/sonata-project/block-bundle/src/Twig/Extension/BlockExtension.php';
include_once \dirname(__DIR__, 4).'/vendor/sonata-project/block-bundle/src/Templating/Helper/BlockHelper.php';
include_once \dirname(__DIR__, 4).'/vendor/willdurand/hateoas/src/Hateoas/Twig/Extension/LinkExtension.php';
include_once \dirname(__DIR__, 4).'/vendor/jms/serializer/src/JMS/Serializer/Twig/SerializerRuntimeExtension.php';
include_once \dirname(__DIR__, 4).'/vendor/knplabs/knp-menu/src/Knp/Menu/Twig/MenuExtension.php';
include_once \dirname(__DIR__, 4).'/vendor/knplabs/knp-menu/src/Knp/Menu/Twig/Helper.php';
include_once \dirname(__DIR__, 4).'/vendor/knplabs/knp-menu/src/Knp/Menu/Renderer/RendererProviderInterface.php';
include_once \dirname(__DIR__, 4).'/vendor/knplabs/knp-menu/src/Knp/Menu/Renderer/PsrProvider.php';
include_once \dirname(__DIR__, 4).'/vendor/knplabs/knp-menu/src/Knp/Menu/Util/MenuManipulator.php';
include_once \dirname(__DIR__, 4).'/vendor/liip/imagine-bundle/Templating/FilterTrait.php';
include_once \dirname(__DIR__, 4).'/vendor/liip/imagine-bundle/Templating/FilterExtension.php';
include_once \dirname(__DIR__, 4).'/vendor/white-october/pagerfanta-bundle/Twig/PagerfantaExtension.php';
include_once \dirname(__DIR__, 4).'/vendor/pagerfanta/pagerfanta/lib/Core/View/ViewFactoryInterface.php';
include_once \dirname(__DIR__, 4).'/vendor/pagerfanta/pagerfanta/lib/Core/View/ViewFactory.php';
include_once \dirname(__DIR__, 4).'/vendor/pagerfanta/pagerfanta/lib/Core/View/ViewInterface.php';
include_once \dirname(__DIR__, 4).'/vendor/pagerfanta/pagerfanta/lib/Core/View/View.php';
include_once \dirname(__DIR__, 4).'/vendor/pagerfanta/pagerfanta/lib/Core/View/TemplateView.php';
include_once \dirname(__DIR__, 4).'/vendor/pagerfanta/pagerfanta/lib/Core/View/DefaultView.php';
include_once \dirname(__DIR__, 4).'/vendor/white-october/pagerfanta-bundle/View/TranslatedView.php';
include_once \dirname(__DIR__, 4).'/vendor/white-october/pagerfanta-bundle/View/DefaultTranslatedView.php';
include_once \dirname(__DIR__, 4).'/vendor/pagerfanta/pagerfanta/lib/Core/View/TwitterBootstrapView.php';
include_once \dirname(__DIR__, 4).'/vendor/pagerfanta/pagerfanta/lib/Core/View/TwitterBootstrap3View.php';
include_once \dirname(__DIR__, 4).'/vendor/pagerfanta/pagerfanta/lib/Core/View/TwitterBootstrap4View.php';
include_once \dirname(__DIR__, 4).'/vendor/pagerfanta/pagerfanta/lib/Core/View/SemanticUiView.php';
include_once \dirname(__DIR__, 4).'/vendor/white-october/pagerfanta-bundle/View/TwitterBootstrapTranslatedView.php';
include_once \dirname(__DIR__, 4).'/vendor/white-october/pagerfanta-bundle/View/TwitterBootstrap4TranslatedView.php';
include_once \dirname(__DIR__, 4).'/vendor/white-october/pagerfanta-bundle/View/TwitterBootstrap3TranslatedView.php';
include_once \dirname(__DIR__, 4).'/vendor/white-october/pagerfanta-bundle/View/SemanticUiTranslatedView.php';
include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/ShopBundle/Twig/OrderTaxesTotalExtension.php';
include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/ShopBundle/Twig/OrderItemsSubtotalExtension.php';
include_once \dirname(__DIR__, 4).'/vendor/friendsofsymfony/ckeditor-bundle/src/Renderer/CKEditorRendererInterface.php';
include_once \dirname(__DIR__, 4).'/vendor/friendsofsymfony/ckeditor-bundle/src/Twig/CKEditorExtension.php';
include_once \dirname(__DIR__, 4).'/vendor/friendsofsymfony/ckeditor-bundle/src/Renderer/CKEditorRenderer.php';
include_once \dirname(__DIR__, 4).'/vendor/friendsofsymfony/ckeditor-bundle/src/Builder/JsonBuilder.php';
include_once \dirname(__DIR__, 4).'/vendor/symfony/twig-bridge/AppVariable.php';
include_once \dirname(__DIR__, 4).'/vendor/twig/twig/src/RuntimeLoader/RuntimeLoaderInterface.php';
include_once \dirname(__DIR__, 4).'/vendor/twig/twig/src/RuntimeLoader/ContainerRuntimeLoader.php';
include_once \dirname(__DIR__, 4).'/vendor/sonata-project/block-bundle/src/Twig/GlobalVariables.php';
include_once \dirname(__DIR__, 4).'/vendor/symfony/twig-bundle/DependencyInjection/Configurator/EnvironmentConfigurator.php';
include_once \dirname(__DIR__, 4).'/vendor/sylius/theme-bundle/src/Asset/PathResolverInterface.php';
include_once \dirname(__DIR__, 4).'/vendor/sylius/theme-bundle/src/Asset/PathResolver.php';
include_once \dirname(__DIR__, 4).'/vendor/symfony/stopwatch/Stopwatch.php';
include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/AddressingBundle/Twig/CountryNameExtension.php';
include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/UiBundle/Twig/TestFormAttributeExtension.php';
include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/UiBundle/Twig/TestHtmlAttributeExtension.php';
include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/UiBundle/Twig/MergeRecursiveExtension.php';
include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/AdminBundle/Twig/NotificationWidgetExtension.php';
include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/AdminBundle/Twig/ShopExtension.php';
include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/AdminBundle/Twig/OrderUnitTaxesExtension.php';
include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/ShopBundle/Calculator/OrderItemsSubtotalCalculatorInterface.php';
include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/ShopBundle/Calculator/OrderItemsSubtotalCalculator.php';

$a = ($this->privates['sylius.theme.templating.file_locator'] ?? $this->load('getSylius_Theme_Templating_FileLocatorService.php'));
$b = ($this->privates['templating.name_parser'] ?? $this->load('getTemplating_NameParserService.php'));

$c = new \Symfony\Bundle\TwigBundle\Loader\FilesystemLoader($a, $b, \dirname(__DIR__, 4));
$c->addPath((\dirname(__DIR__, 4).'/vendor/knplabs/knp-menu/src/Knp/Menu/Resources/views'));
$c->addPath((\dirname(__DIR__, 4).'/templates'));
$c->addPath((\dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Resources/views'), 'Framework');
$c->addPath((\dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Resources/views'), '!Framework');
$c->addPath((\dirname(__DIR__, 4).'/vendor/symfony/security-bundle/Resources/views'), 'Security');
$c->addPath((\dirname(__DIR__, 4).'/vendor/symfony/security-bundle/Resources/views'), '!Security');
$c->addPath((\dirname(__DIR__, 4).'/vendor/symfony/swiftmailer-bundle/Resources/views'), 'Swiftmailer');
$c->addPath((\dirname(__DIR__, 4).'/vendor/symfony/swiftmailer-bundle/Resources/views'), '!Swiftmailer');
$c->addPath((\dirname(__DIR__, 4).'/templates/bundles/TwigBundle'), 'Twig');
$c->addPath((\dirname(__DIR__, 4).'/vendor/symfony/twig-bundle/Resources/views'), 'Twig');
$c->addPath((\dirname(__DIR__, 4).'/vendor/symfony/twig-bundle/Resources/views'), '!Twig');
$c->addPath((\dirname(__DIR__, 4).'/vendor/doctrine/doctrine-bundle/Resources/views'), 'Doctrine');
$c->addPath((\dirname(__DIR__, 4).'/vendor/doctrine/doctrine-bundle/Resources/views'), '!Doctrine');
$c->addPath((\dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/ChannelBundle/Resources/views'), 'SyliusChannel');
$c->addPath((\dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/ChannelBundle/Resources/views'), '!SyliusChannel');
$c->addPath((\dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/AttributeBundle/Resources/views'), 'SyliusAttribute');
$c->addPath((\dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/AttributeBundle/Resources/views'), '!SyliusAttribute');
$c->addPath((\dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/UiBundle/Resources/views'), 'SyliusUi');
$c->addPath((\dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/UiBundle/Resources/views'), '!SyliusUi');
$c->addPath((\dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/CoreBundle/Resources/views'), 'SyliusCore');
$c->addPath((\dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/CoreBundle/Resources/views'), '!SyliusCore');
$c->addPath((\dirname(__DIR__, 4).'/vendor/sylius/resource-bundle/src/Bundle/Resources/views'), 'SyliusResource');
$c->addPath((\dirname(__DIR__, 4).'/vendor/sylius/resource-bundle/src/Bundle/Resources/views'), '!SyliusResource');
$c->addPath((\dirname(__DIR__, 4).'/vendor/sonata-project/block-bundle/src/Resources/views'), 'SonataBlock');
$c->addPath((\dirname(__DIR__, 4).'/vendor/sonata-project/block-bundle/src/Resources/views'), '!SonataBlock');
$c->addPath((\dirname(__DIR__, 4).'/vendor/knplabs/knp-menu-bundle/src/Resources/views'), 'KnpMenu');
$c->addPath((\dirname(__DIR__, 4).'/vendor/knplabs/knp-menu-bundle/src/Resources/views'), '!KnpMenu');
$c->addPath((\dirname(__DIR__, 4).'/vendor/liip/imagine-bundle/Resources/views'), 'LiipImagine');
$c->addPath((\dirname(__DIR__, 4).'/vendor/liip/imagine-bundle/Resources/views'), '!LiipImagine');
$c->addPath((\dirname(__DIR__, 4).'/vendor/payum/payum-bundle/Resources/views'), 'Payum');
$c->addPath((\dirname(__DIR__, 4).'/vendor/payum/payum-bundle/Resources/views'), '!Payum');
$c->addPath((\dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/PayumBundle/Resources/views'), 'SyliusPayum');
$c->addPath((\dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/PayumBundle/Resources/views'), '!SyliusPayum');
$c->addPath((\dirname(__DIR__, 4).'/vendor/sylius/theme-bundle/src/Resources/views'), 'SyliusTheme');
$c->addPath((\dirname(__DIR__, 4).'/vendor/sylius/theme-bundle/src/Resources/views'), '!SyliusTheme');
$c->addPath((\dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/AdminBundle/Resources/views'), 'SyliusAdmin');
$c->addPath((\dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/AdminBundle/Resources/views'), '!SyliusAdmin');
$c->addPath((\dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/ShopBundle/Resources/views'), 'SyliusShop');
$c->addPath((\dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/ShopBundle/Resources/views'), '!SyliusShop');
$c->addPath((\dirname(__DIR__, 4).'/vendor/friendsofsymfony/oauth-server-bundle/Resources/views'), 'FOSOAuthServer');
$c->addPath((\dirname(__DIR__, 4).'/vendor/friendsofsymfony/oauth-server-bundle/Resources/views'), '!FOSOAuthServer');
$c->addPath((\dirname(__DIR__, 4).'/vendor/stefandoorn/sitemap-plugin/src/Resources/views'), 'SitemapPlugin');
$c->addPath((\dirname(__DIR__, 4).'/vendor/stefandoorn/sitemap-plugin/src/Resources/views'), '!SitemapPlugin');
$c->addPath((\dirname(__DIR__, 4).'/vendor/friendsofsymfony/ckeditor-bundle/src/Resources/views'), 'FOSCKEditor');
$c->addPath((\dirname(__DIR__, 4).'/vendor/friendsofsymfony/ckeditor-bundle/src/Resources/views'), '!FOSCKEditor');
$c->addPath((\dirname(__DIR__, 4).'/vendor/bitbag/cms-plugin/src/Resources/views'), 'BitBagSyliusCmsPlugin');
$c->addPath((\dirname(__DIR__, 4).'/vendor/bitbag/cms-plugin/src/Resources/views'), '!BitBagSyliusCmsPlugin');
$c->addPath((\dirname(__DIR__, 4).'/templates'));
$c->addPath((\dirname(__DIR__, 4).'/vendor/symfony/twig-bridge/Resources/views/Email'), 'email');
$c->addPath((\dirname(__DIR__, 4).'/vendor/symfony/twig-bridge/Resources/views/Email'), '!email');
$c->addPath((\dirname(__DIR__, 4).'/vendor/symfony/twig-bridge/Resources/views/Form'));

$this->services['twig'] = $instance = new \Twig\Environment(new \Sylius\Bundle\ThemeBundle\Twig\ThemeFilesystemLoader($c, $a, $b), ['debug' => false, 'strict_variables' => false, 'autoescape' => 'name', 'cache' => ($this->targetDir.''.'/twig'), 'charset' => 'UTF-8']);

$d = ($this->services['translator'] ?? $this->getTranslatorService());
$e = ($this->services['request_stack'] ?? ($this->services['request_stack'] = new \Symfony\Component\HttpFoundation\RequestStack()));

$f = new \Symfony\Component\Asset\Packages(new \Sylius\Bundle\ThemeBundle\Asset\Package\PathPackage('', new \Symfony\Component\Asset\VersionStrategy\EmptyVersionStrategy(), ($this->privates['sylius.theme.context.channel_based'] ?? $this->getSylius_Theme_Context_ChannelBasedService()), ($this->services['Sylius\\Bundle\\ThemeBundle\\Asset\\PathResolverInterface'] ?? ($this->services['Sylius\\Bundle\\ThemeBundle\\Asset\\PathResolverInterface'] = new \Sylius\Bundle\ThemeBundle\Asset\PathResolver())), new \Symfony\Component\Asset\Context\RequestStackContext($e, '', false)), []);
$g = ($this->services['router'] ?? $this->getRouterService());
$h = ($this->privates['debug.stopwatch'] ?? ($this->privates['debug.stopwatch'] = new \Symfony\Component\Stopwatch\Stopwatch(true)));
$i = new \Knp\Menu\Util\MenuManipulator();
$j = ($this->services['knp_menu.matcher'] ?? $this->load('getKnpMenu_MatcherService.php'));
$k = new \Pagerfanta\View\ViewFactory();

$l = new \Pagerfanta\View\DefaultView();
$m = new \Pagerfanta\View\TwitterBootstrapView();
$n = new \Pagerfanta\View\TwitterBootstrap3View();
$o = new \Pagerfanta\View\TwitterBootstrap4View();
$p = new \Pagerfanta\View\SemanticUiView();

$k->add(['default' => $l, 'default_translated' => new \WhiteOctober\PagerfantaBundle\View\DefaultTranslatedView($l, $d), 'twitter_bootstrap' => $m, 'twitter_bootstrap3' => $n, 'twitter_bootstrap4' => $o, 'semantic_ui' => $p, 'twitter_bootstrap4_translated' => new \WhiteOctober\PagerfantaBundle\View\TwitterBootstrap4TranslatedView($o, $d), 'twitter_bootstrap3_translated' => new \WhiteOctober\PagerfantaBundle\View\TwitterBootstrap3TranslatedView($n, $d), 'twitter_bootstrap_translated' => new \WhiteOctober\PagerfantaBundle\View\TwitterBootstrapTranslatedView($m, $d), 'semantic_ui_translated' => new \WhiteOctober\PagerfantaBundle\View\SemanticUiTranslatedView($p, $d)]);
$q = new \Symfony\Bridge\Twig\AppVariable();
$q->setEnvironment('prod');
$q->setDebug(false);
if ($this->has('security.token_storage')) {
    $q->setTokenStorage(($this->services['security.token_storage'] ?? $this->getSecurity_TokenStorageService()));
}
if ($this->has('request_stack')) {
    $q->setRequestStack($e);
}

$instance->addExtension(new \Symfony\Bridge\Twig\Extension\CsrfExtension());
$instance->addExtension(new \Symfony\Bridge\Twig\Extension\LogoutUrlExtension(($this->privates['security.logout_url_generator'] ?? $this->getSecurity_LogoutUrlGeneratorService())));
$instance->addExtension(new \Symfony\Bridge\Twig\Extension\SecurityExtension(($this->services['security.authorization_checker'] ?? $this->getSecurity_AuthorizationCheckerService())));
$instance->addExtension(new \Symfony\Bridge\Twig\Extension\TranslationExtension($d));
$instance->addExtension(new \Symfony\Bridge\Twig\Extension\AssetExtension($f));
$instance->addExtension(new \Symfony\Bridge\Twig\Extension\CodeExtension(($this->privates['debug.file_link_formatter'] ?? ($this->privates['debug.file_link_formatter'] = new \Symfony\Component\HttpKernel\Debug\FileLinkFormatter(NULL))), \dirname(__DIR__, 4), 'UTF-8'));
$instance->addExtension(new \Symfony\Bridge\Twig\Extension\RoutingExtension($g));
$instance->addExtension(new \Symfony\Bridge\Twig\Extension\YamlExtension());
$instance->addExtension(new \Symfony\Bridge\Twig\Extension\StopwatchExtension($h, false));
$instance->addExtension(new \Symfony\Bridge\Twig\Extension\ExpressionExtension());
$instance->addExtension(new \Symfony\Bridge\Twig\Extension\HttpKernelExtension());
$instance->addExtension(new \Symfony\Bridge\Twig\Extension\HttpFoundationExtension(new \Symfony\Component\HttpFoundation\UrlHelper($e, ($this->privates['router.request_context'] ?? $this->getRouter_RequestContextService()))));
$instance->addExtension(new \Symfony\Bridge\Twig\Extension\FormExtension());
$instance->addExtension(new \Twig\Extra\Intl\IntlExtension());
$instance->addExtension(new \Sylius\Bundle\MoneyBundle\Twig\ConvertMoneyExtension(($this->services['sylius.templating.helper.convert_money'] ?? $this->load('getSylius_Templating_Helper_ConvertMoneyService.php'))));
$instance->addExtension(new \Doctrine\Bundle\DoctrineBundle\Twig\DoctrineExtension());
$instance->addExtension(new \Sylius\Bundle\OrderBundle\Twig\AggregateAdjustmentsExtension(($this->services['sylius.templating.helper.adjustment'] ?? $this->load('getSylius_Templating_Helper_AdjustmentService.php'))));
$instance->addExtension(new \Sylius\Bundle\MoneyBundle\Twig\FormatMoneyExtension(($this->services['sylius.templating.helper.format_money'] ?? $this->load('getSylius_Templating_Helper_FormatMoneyService.php'))));
$instance->addExtension(new \Sylius\Bundle\CurrencyBundle\Twig\CurrencyExtension(($this->services['sylius.templating.helper.currency'] ?? $this->load('getSylius_Templating_Helper_CurrencyService.php'))));
$instance->addExtension(new \Sylius\Bundle\LocaleBundle\Twig\LocaleExtension(($this->services['sylius.templating.helper.locale'] ?? $this->load('getSylius_Templating_Helper_LocaleService.php'))));
$instance->addExtension(($this->services['sylius.twig.extension.country_name'] ?? ($this->services['sylius.twig.extension.country_name'] = new \Sylius\Bundle\AddressingBundle\Twig\CountryNameExtension(''))));
$instance->addExtension(($this->services['sylius.twig.extension.province_naming'] ?? $this->load('getSylius_Twig_Extension_ProvinceNamingService.php')));
$instance->addExtension(new \Sylius\Bundle\InventoryBundle\Twig\InventoryExtension(($this->services['sylius.templating.helper.inventory'] ?? $this->load('getSylius_Templating_Helper_InventoryService.php'))));
$instance->addExtension(new \Sylius\Bundle\UiBundle\Twig\PercentageExtension());
$instance->addExtension(($this->services['sylius.twig.extension.form_test_attribute_array'] ?? ($this->services['sylius.twig.extension.form_test_attribute_array'] = new \Sylius\Bundle\UiBundle\Twig\TestFormAttributeExtension('prod'))));
$instance->addExtension(($this->services['sylius.twig.extension.form_test_attribute_name'] ?? ($this->services['sylius.twig.extension.form_test_attribute_name'] = new \Sylius\Bundle\UiBundle\Twig\TestHtmlAttributeExtension('prod'))));
$instance->addExtension(new \Sylius\Bundle\UiBundle\Twig\SortByExtension());
$instance->addExtension(new \Sylius\Bundle\UiBundle\Twig\TemplateEventExtension(new \Sylius\Bundle\UiBundle\Renderer\DelegatingTemplateEventRenderer(($this->privates['Sylius\\Bundle\\UiBundle\\Registry\\TemplateBlockRegistryInterface'] ?? $this->load('getTemplateBlockRegistryInterfaceService.php')), new \Sylius\Bundle\UiBundle\Renderer\TwigTemplateBlockRenderer($instance))));
$instance->addExtension(($this->services['sylius.twig.extension.merge_recursive'] ?? ($this->services['sylius.twig.extension.merge_recursive'] = new \Sylius\Bundle\UiBundle\Twig\MergeRecursiveExtension())));
$instance->addExtension(($this->services['Sylius\\Bundle\\UiBundle\\Twig\\LegacySonataBlockExtension'] ?? $this->load('getLegacySonataBlockExtensionService.php')));
$instance->addExtension(($this->services['sylius.twig.extension.sylius_bundle_loaded_checker'] ?? $this->load('getSylius_Twig_Extension_SyliusBundleLoadedCheckerService.php')));
$instance->addExtension(new \Sylius\Bundle\CoreBundle\Twig\PriceExtension(($this->services['sylius.templating.helper.price'] ?? $this->load('getSylius_Templating_Helper_PriceService.php'))));
$instance->addExtension(new \Sylius\Bundle\CoreBundle\Twig\VariantResolverExtension(($this->services['sylius.templating.helper.variant_resolver'] ?? $this->load('getSylius_Templating_Helper_VariantResolverService.php'))));
$instance->addExtension(new \Sylius\Bundle\CoreBundle\Twig\ProductVariantsPricesExtension(($this->services['sylius.templating.helper.product_variants_prices'] ?? $this->load('getSylius_Templating_Helper_ProductVariantsPricesService.php'))));
$instance->addExtension(new \Sylius\Bundle\CoreBundle\Twig\CheckoutStepsExtension(($this->services['sylius.templating.helper.checkout_steps'] ?? $this->load('getSylius_Templating_Helper_CheckoutStepsService.php'))));
$instance->addExtension(new \Sylius\Bundle\GridBundle\Twig\GridExtension(($this->services['sylius.templating.helper.grid'] ?? $this->load('getSylius_Templating_Helper_GridService.php'))));
$instance->addExtension(new \Sylius\Bundle\GridBundle\Twig\BulkActionGridExtension(($this->services['sylius.templating.helper.bulk_action_grid'] ?? $this->load('getSylius_Templating_Helper_BulkActionGridService.php'))));
$instance->addExtension(new \SM\Extension\Twig\SMExtension(($this->services['sm.factory'] ?? $this->getSm_FactoryService())));
$instance->addExtension(new \Sonata\BlockBundle\Twig\Extension\BlockExtension(new \Sonata\BlockBundle\Templating\Helper\BlockHelper(($this->services['sonata.block.manager'] ?? $this->load('getSonata_Block_ManagerService.php')), $this->parameters['sonata_block.cache_blocks'], ($this->services['sonata.block.renderer.default'] ?? $this->load('getSonata_Block_Renderer_DefaultService.php')), ($this->services['sonata.block.context_manager.default'] ?? $this->load('getSonata_Block_ContextManager_DefaultService.php')), ($this->services['event_dispatcher'] ?? $this->getEventDispatcherService()), NULL, ($this->privates['sonata.block.cache.handler.default'] ?? ($this->privates['sonata.block.cache.handler.default'] = new \Sonata\BlockBundle\Cache\HttpCacheHandler())), $h)));
$instance->addExtension(new \Hateoas\Twig\Extension\LinkExtension(($this->services['hateoas.helper.link'] ?? $this->load('getHateoas_Helper_LinkService.php'))));
$instance->addExtension(new \JMS\Serializer\Twig\SerializerRuntimeExtension());
$instance->addExtension(new \Knp\Menu\Twig\MenuExtension(new \Knp\Menu\Twig\Helper(new \Knp\Menu\Renderer\PsrProvider(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'list' => ['privates', 'knp_menu.renderer.list', 'getKnpMenu_Renderer_ListService.php', true],
    'twig' => ['privates', 'knp_menu.renderer.twig', 'getKnpMenu_Renderer_TwigService.php', true],
], [
    'list' => '?',
    'twig' => '?',
]), 'twig', [], false), ($this->privates['knp_menu.menu_provider.chain'] ?? $this->load('getKnpMenu_MenuProvider_ChainService.php')), $i, $j), $j, $i));
$instance->addExtension(new \Liip\ImagineBundle\Templating\FilterExtension(($this->services['liip_imagine.cache.manager'] ?? $this->load('getLiipImagine_Cache_ManagerService.php'))));
$instance->addExtension(new \WhiteOctober\PagerfantaBundle\Twig\PagerfantaExtension('default', $k, $g, $e));
$instance->addExtension(($this->services['sylius.twig.extension.widget.admin_notification'] ?? ($this->services['sylius.twig.extension.widget.admin_notification'] = new \Sylius\Bundle\AdminBundle\Twig\NotificationWidgetExtension(true, 60))));
$instance->addExtension(($this->services['sylius.twig.extension.shop'] ?? ($this->services['sylius.twig.extension.shop'] = new \Sylius\Bundle\AdminBundle\Twig\ShopExtension(true))));
$instance->addExtension(($this->services['sylius.twig.extension.channels_currencies'] ?? $this->load('getSylius_Twig_Extension_ChannelsCurrenciesService.php')));
$instance->addExtension(($this->services['Sylius\\Bundle\\AdminBundle\\Twig\\OrderUnitTaxesExtension'] ?? ($this->services['Sylius\\Bundle\\AdminBundle\\Twig\\OrderUnitTaxesExtension'] = new \Sylius\Bundle\AdminBundle\Twig\OrderUnitTaxesExtension())));
$instance->addExtension(($this->services['Sylius\\Bundle\\AdminBundle\\Twig\\ChannelNameExtension'] ?? $this->load('getChannelNameExtensionService.php')));
$instance->addExtension(new \Sylius\Bundle\ShopBundle\Twig\OrderTaxesTotalExtension());
$instance->addExtension(new \Sylius\Bundle\ShopBundle\Twig\OrderItemsSubtotalExtension(($this->services['sylius.calculator.order_items_subtotal'] ?? ($this->services['sylius.calculator.order_items_subtotal'] = new \Sylius\Bundle\ShopBundle\Calculator\OrderItemsSubtotalCalculator()))));
$instance->addExtension(new \FOS\CKEditorBundle\Twig\CKEditorExtension(new \FOS\CKEditorBundle\Renderer\CKEditorRenderer(new \FOS\CKEditorBundle\Builder\JsonBuilder(($this->privates['property_accessor'] ?? $this->load('getPropertyAccessorService.php'))), $g, $f, $e, $instance, (($this->hasParameter("locale")) ? ($this->getParameter("locale")) : (null)))));
$instance->addGlobal('app', $q);
$instance->addRuntimeLoader(new \Twig\RuntimeLoader\ContainerRuntimeLoader(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'JMS\\Serializer\\Twig\\SerializerRuntimeHelper' => ['services', 'jms_serializer.twig_extension.serializer_runtime_helper', 'getJmsSerializer_TwigExtension_SerializerRuntimeHelperService.php', true],
    'Symfony\\Bridge\\Twig\\Extension\\CsrfRuntime' => ['privates', 'twig.runtime.security_csrf', 'getTwig_Runtime_SecurityCsrfService.php', true],
    'Symfony\\Bridge\\Twig\\Extension\\HttpKernelRuntime' => ['privates', 'twig.runtime.httpkernel', 'getTwig_Runtime_HttpkernelService.php', true],
    'Symfony\\Component\\Form\\FormRenderer' => ['privates', 'twig.form.renderer', 'getTwig_Form_RendererService.php', true],
], [
    'JMS\\Serializer\\Twig\\SerializerRuntimeHelper' => '?',
    'Symfony\\Bridge\\Twig\\Extension\\CsrfRuntime' => '?',
    'Symfony\\Bridge\\Twig\\Extension\\HttpKernelRuntime' => '?',
    'Symfony\\Component\\Form\\FormRenderer' => '?',
])));
$instance->addGlobal('sylius', ($this->services['sylius.context.shopper'] ?? $this->getSylius_Context_ShopperService()));
$instance->addGlobal('sylius_base_locale', 'en_US');
$instance->addGlobal('sylius_meta', ['version' => '1.7.6']);
$instance->addGlobal('sonata_block', new \Sonata\BlockBundle\Twig\GlobalVariables(['block_base' => '@SonataBlock/Block/block_base.html.twig', 'block_container' => '@SonataBlock/Block/block_container.html.twig']));
(new \Symfony\Bundle\TwigBundle\DependencyInjection\Configurator\EnvironmentConfigurator('F j, Y H:i', '%d days', NULL, 0, '.', ','))->configure($instance);

return $instance;
