<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Sylius\Component\Addressing\Factory\ZoneFactoryInterface' shared service.

include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Component/Addressing/Factory/ZoneFactoryInterface.php';
include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Component/Addressing/Factory/ZoneFactory.php';

return $this->services['Sylius\\Component\\Addressing\\Factory\\ZoneFactoryInterface'] = new \Sylius\Component\Addressing\Factory\ZoneFactory(new \Sylius\Component\Resource\Factory\Factory('App\\Entity\\Addressing\\Zone'), ($this->services['sylius.factory.zone_member'] ?? ($this->services['sylius.factory.zone_member'] = new \Sylius\Component\Resource\Factory\Factory('App\\Entity\\Addressing\\ZoneMember'))));
