<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerS2VlfZP\srcApp_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerS2VlfZP/srcApp_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerS2VlfZP.legacy');

    return;
}

if (!\class_exists(srcApp_KernelProdContainer::class, false)) {
    \class_alias(\ContainerS2VlfZP\srcApp_KernelProdContainer::class, srcApp_KernelProdContainer::class, false);
}

return new \ContainerS2VlfZP\srcApp_KernelProdContainer([
    'container.build_hash' => 'S2VlfZP',
    'container.build_id' => 'a16d9c5d',
    'container.build_time' => 1598136864,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerS2VlfZP');
