<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Sylius\Bundle\UiBundle\Command\DebugTemplateEventCommand' shared service.

include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/UiBundle/Command/DebugTemplateEventCommand.php';

$this->privates['Sylius\\Bundle\\UiBundle\\Command\\DebugTemplateEventCommand'] = $instance = new \Sylius\Bundle\UiBundle\Command\DebugTemplateEventCommand(($this->privates['Sylius\\Bundle\\UiBundle\\Registry\\TemplateBlockRegistryInterface'] ?? $this->load('getTemplateBlockRegistryInterfaceService.php')));

$instance->setName('sylius:debug:template-event');

return $instance;
