<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sylius.registry.shipping_calculator' shared service.

include_once \dirname(__DIR__, 4).'/vendor/sylius/registry/src/ServiceRegistryInterface.php';
include_once \dirname(__DIR__, 4).'/vendor/sylius/registry/src/ServiceRegistry.php';
include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Component/Shipping/Calculator/CalculatorInterface.php';
include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Component/Core/Shipping/Calculator/FlatRateCalculator.php';
include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Component/Core/Shipping/Calculator/PerUnitRateCalculator.php';

$this->services['sylius.registry.shipping_calculator'] = $instance = new \Sylius\Component\Registry\ServiceRegistry('Sylius\\Component\\Shipping\\Calculator\\CalculatorInterface', 'shipping calculator');

$instance->register('flat_rate', ($this->services['sylius.shipping_calculator.flat_rate'] ?? ($this->services['sylius.shipping_calculator.flat_rate'] = new \Sylius\Component\Core\Shipping\Calculator\FlatRateCalculator())));
$instance->register('per_unit_rate', ($this->services['sylius.shipping_calculator.per_unit_rate'] ?? ($this->services['sylius.shipping_calculator.per_unit_rate'] = new \Sylius\Component\Core\Shipping\Calculator\PerUnitRateCalculator())));

return $instance;
