<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sylius.form.type.autocomplete_product_taxon_choice' shared service.

include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/CoreBundle/Form/Type/Taxon/ProductTaxonAutocompleteChoiceType.php';

return $this->services['sylius.form.type.autocomplete_product_taxon_choice'] = new \Sylius\Bundle\CoreBundle\Form\Type\Taxon\ProductTaxonAutocompleteChoiceType(($this->services['sylius.factory.product_taxon'] ?? ($this->services['sylius.factory.product_taxon'] = new \Sylius\Component\Resource\Factory\Factory('App\\Entity\\Product\\ProductTaxon'))), ($this->services['sylius.repository.product_taxon'] ?? $this->load('getSylius_Repository_ProductTaxonService.php')));
