<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sylius.admin_user.listener.update_user_encoder' shared service.

include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/UserBundle/EventListener/UpdateUserEncoderListener.php';

return $this->privates['sylius.admin_user.listener.update_user_encoder'] = new \Sylius\Bundle\UserBundle\EventListener\UpdateUserEncoderListener(($this->services['doctrine.orm.default_entity_manager'] ?? $this->getDoctrine_Orm_DefaultEntityManagerService()), 'argon2i', 'App\\Entity\\User\\AdminUser', 'Sylius\\Component\\Core\\Model\\AdminUserInterface', '_password');
