<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sonata.block.manager' shared service.

include_once \dirname(__DIR__, 4).'/vendor/sonata-project/block-bundle/src/Block/BlockServiceManagerInterface.php';
include_once \dirname(__DIR__, 4).'/vendor/sonata-project/block-bundle/src/Block/BlockServiceManager.php';

$this->services['sonata.block.manager'] = $instance = new \Sonata\BlockBundle\Block\BlockServiceManager($this, false, ($this->privates['monolog.logger'] ?? $this->load('getMonolog_LoggerService.php')));

$instance->add('sonata.block.service.container', 'sonata.block.service.container', []);
$instance->add('sonata.block.service.empty', 'sonata.block.service.empty', []);
$instance->add('sonata.block.service.text', 'sonata.block.service.text', []);
$instance->add('sonata.block.service.rss', 'sonata.block.service.rss', []);
$instance->add('sonata.block.service.template', 'sonata.block.service.template', []);
$instance->add('sonata.block.service.menu', 'sonata.block.service.menu', []);

return $instance;
