<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Sylius\Bundle\ThemeBundle\Templating\Locator\TemplateLocatorInterface' shared service.

include_once \dirname(__DIR__, 4).'/vendor/sylius/theme-bundle/src/Templating/Locator/TemplateLocatorInterface.php';
include_once \dirname(__DIR__, 4).'/vendor/sylius/theme-bundle/src/Templating/Locator/CachedTemplateLocator.php';
include_once \dirname(__DIR__, 4).'/vendor/sylius/theme-bundle/src/Templating/Locator/TemplateLocator.php';
include_once \dirname(__DIR__, 4).'/vendor/doctrine/cache/lib/Doctrine/Common/Cache/Cache.php';
include_once \dirname(__DIR__, 4).'/vendor/doctrine/cache/lib/Doctrine/Common/Cache/FlushableCache.php';
include_once \dirname(__DIR__, 4).'/vendor/doctrine/cache/lib/Doctrine/Common/Cache/ClearableCache.php';
include_once \dirname(__DIR__, 4).'/vendor/doctrine/cache/lib/Doctrine/Common/Cache/MultiGetCache.php';
include_once \dirname(__DIR__, 4).'/vendor/doctrine/cache/lib/Doctrine/Common/Cache/MultiDeleteCache.php';
include_once \dirname(__DIR__, 4).'/vendor/doctrine/cache/lib/Doctrine/Common/Cache/MultiPutCache.php';
include_once \dirname(__DIR__, 4).'/vendor/doctrine/cache/lib/Doctrine/Common/Cache/MultiOperationCache.php';
include_once \dirname(__DIR__, 4).'/vendor/doctrine/cache/lib/Doctrine/Common/Cache/CacheProvider.php';
include_once \dirname(__DIR__, 4).'/vendor/doctrine/cache/lib/Doctrine/Common/Cache/ArrayCache.php';

return $this->services['Sylius\\Bundle\\ThemeBundle\\Templating\\Locator\\TemplateLocatorInterface'] = new \Sylius\Bundle\ThemeBundle\Templating\Locator\CachedTemplateLocator(new \Sylius\Bundle\ThemeBundle\Templating\Locator\TemplateLocator(($this->services['Sylius\\Bundle\\ThemeBundle\\Locator\\ResourceLocatorInterface'] ?? $this->load('getResourceLocatorInterfaceService.php'))), ($this->services['sylius.theme.templating.cache'] ?? ($this->services['sylius.theme.templating.cache'] = new \Doctrine\Common\Cache\ArrayCache())));
