<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Sylius\Component\Taxonomy\Factory\TaxonFactoryInterface' shared service.

include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Component/Taxonomy/Factory/TaxonFactoryInterface.php';
include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Component/Taxonomy/Factory/TaxonFactory.php';
include_once \dirname(__DIR__, 4).'/vendor/sylius/resource-bundle/src/Component/Factory/TranslatableFactoryInterface.php';
include_once \dirname(__DIR__, 4).'/vendor/sylius/resource-bundle/src/Component/Factory/TranslatableFactory.php';

return $this->services['Sylius\\Component\\Taxonomy\\Factory\\TaxonFactoryInterface'] = new \Sylius\Component\Taxonomy\Factory\TaxonFactory(new \Sylius\Component\Resource\Factory\TranslatableFactory(new \Sylius\Component\Resource\Factory\Factory('App\\Entity\\Taxonomy\\Taxon'), ($this->services['sylius.translation_locale_provider.admin'] ?? $this->getSylius_TranslationLocaleProvider_AdminService())));
