<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Sonata\BlockBundle\Command\DebugBlocksCommand' shared service.

include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
include_once \dirname(__DIR__, 4).'/vendor/sonata-project/block-bundle/src/Command/DebugBlocksCommand.php';

$this->privates['Sonata\\BlockBundle\\Command\\DebugBlocksCommand'] = $instance = new \Sonata\BlockBundle\Command\DebugBlocksCommand(($this->services['sonata.block.manager'] ?? $this->getSonata_Block_ManagerService()));

$instance->setName('debug:sonata:block');

return $instance;
