<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'fos_rest.exception_listener' shared service.

@trigger_error('The "fos_rest.exception_listener" service is deprecated since FOSRestBundle 2.8.', E_USER_DEPRECATED);

include_once \dirname(__DIR__, 4).'/vendor/symfony/http-kernel/EventListener/ErrorListener.php';

return $this->privates['fos_rest.exception_listener'] = new \FOS\RestBundle\EventListener\ExceptionListener(new \Symfony\Component\HttpKernel\EventListener\ErrorListener('fos_rest.exception.twig_controller::showAction', ($this->privates['monolog.logger.request'] ?? $this->getMonolog_Logger_RequestService()), true), ($this->services['event_dispatcher'] ?? $this->getEventDispatcherService()));
