<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'payum.command.create_capture_token' shared service.

include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
include_once \dirname(__DIR__, 4).'/vendor/symfony/dependency-injection/ContainerAwareInterface.php';
include_once \dirname(__DIR__, 4).'/vendor/symfony/dependency-injection/ContainerAwareTrait.php';
include_once \dirname(__DIR__, 4).'/vendor/payum/payum-bundle/Command/CreateCaptureTokenCommand.php';

$this->privates['payum.command.create_capture_token'] = $instance = new \Payum\Bundle\PayumBundle\Command\CreateCaptureTokenCommand();

$instance->setContainer($this);
$instance->setName('payum:security:create-capture-token');

return $instance;
