<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Sylius\Bundle\AdminBundle\Action\ResendOrderConfirmationEmailAction' shared service.

include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/AdminBundle/Action/ResendOrderConfirmationEmailAction.php';

return $this->services['Sylius\\Bundle\\AdminBundle\\Action\\ResendOrderConfirmationEmailAction'] = new \Sylius\Bundle\AdminBundle\Action\ResendOrderConfirmationEmailAction(($this->services['sylius.repository.order'] ?? $this->getSylius_Repository_OrderService()), ($this->services['Sylius\\Bundle\\AdminBundle\\EmailManager\\OrderEmailManagerInterface'] ?? $this->load('getOrderEmailManagerInterfaceService.php')), ($this->services['security.csrf.token_manager'] ?? $this->load('getSecurity_Csrf_TokenManagerService.php')), ($this->services['session'] ?? $this->getSessionService()));
