<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sylius.listener.user_mailer_listener' shared service.

include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/CoreBundle/EventListener/MailerListener.php';

return $this->privates['sylius.listener.user_mailer_listener'] = new \Sylius\Bundle\CoreBundle\EventListener\MailerListener(($this->services['sylius.email_sender'] ?? $this->load('getSylius_EmailSenderService.php')), ($this->services['sylius.context.channel'] ?? $this->getSylius_Context_ChannelService()), ($this->services['Sylius\\Component\\Locale\\Context\\LocaleContextInterface'] ?? $this->getLocaleContextInterfaceService()));
