<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sylius.form.type.promotion_action.filter.product' shared service.

include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/CoreBundle/Form/Type/Promotion/Filter/ProductFilterConfigurationType.php';

return $this->services['sylius.form.type.promotion_action.filter.product'] = new \Sylius\Bundle\CoreBundle\Form\Type\Promotion\Filter\ProductFilterConfigurationType(($this->services['sylius.form.type.data_transformer.products_to_codes'] ?? $this->load('getSylius_Form_Type_DataTransformer_ProductsToCodesService.php')));
