<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sylius.form.type.channel_choice' shared service.

include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/ChannelBundle/Form/Type/ChannelChoiceType.php';

return $this->services['sylius.form.type.channel_choice'] = new \Sylius\Bundle\ChannelBundle\Form\Type\ChannelChoiceType(($this->services['sylius.repository.channel'] ?? $this->getSylius_Repository_ChannelService()));
