<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sylius.form.type.add_to_cart' shared service.

include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
include_once \dirname(__DIR__, 4).'/vendor/sylius/resource-bundle/src/Bundle/Form/Type/AbstractResourceType.php';
include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/CoreBundle/Form/Type/Order/AddToCartType.php';

return $this->services['sylius.form.type.add_to_cart'] = new \Sylius\Bundle\CoreBundle\Form\Type\Order\AddToCartType('Sylius\\Bundle\\OrderBundle\\Controller\\AddToCartCommand', $this->parameters['sylius.form.type.add_to_cart.validation_groups']);
