<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sylius.fixture.geographical' shared service.

include_once \dirname(__DIR__, 4).'/vendor/sylius/fixtures-bundle/src/Fixture/FixtureInterface.php';
include_once \dirname(__DIR__, 4).'/vendor/sylius/fixtures-bundle/src/Fixture/AbstractFixture.php';
include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/CoreBundle/Fixture/GeographicalFixture.php';

$a = ($this->services['doctrine.orm.default_entity_manager'] ?? $this->getDoctrine_Orm_DefaultEntityManagerService());

return $this->services['sylius.fixture.geographical'] = new \Sylius\Bundle\CoreBundle\Fixture\GeographicalFixture(($this->services['sylius.factory.country'] ?? ($this->services['sylius.factory.country'] = new \Sylius\Component\Resource\Factory\Factory('App\\Entity\\Addressing\\Country'))), $a, ($this->services['sylius.factory.province'] ?? ($this->services['sylius.factory.province'] = new \Sylius\Component\Resource\Factory\Factory('App\\Entity\\Addressing\\Province'))), $a, ($this->services['Sylius\\Component\\Addressing\\Factory\\ZoneFactoryInterface'] ?? $this->load('getZoneFactoryInterfaceService.php')), $a);
