<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sylius_fixtures.fixture_loader' shared service.

include_once \dirname(__DIR__, 4).'/vendor/sylius/fixtures-bundle/src/Loader/FixtureLoaderInterface.php';
include_once \dirname(__DIR__, 4).'/vendor/sylius/fixtures-bundle/src/Loader/HookableFixtureLoader.php';
include_once \dirname(__DIR__, 4).'/vendor/sylius/fixtures-bundle/src/Loader/FixtureLoader.php';

return $this->services['sylius_fixtures.fixture_loader'] = new \Sylius\Bundle\FixturesBundle\Loader\HookableFixtureLoader(new \Sylius\Bundle\FixturesBundle\Loader\FixtureLoader());
