<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sylius.listener.order_integrity_checker' shared service.

include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/ShopBundle/EventListener/OrderIntegrityChecker.php';

return $this->services['sylius.listener.order_integrity_checker'] = new \Sylius\Bundle\ShopBundle\EventListener\OrderIntegrityChecker(($this->services['router'] ?? $this->getRouterService()), ($this->services['sylius.order_processing.order_processor'] ?? $this->load('getSylius_OrderProcessing_OrderProcessorService.php')), ($this->services['doctrine.orm.default_entity_manager'] ?? $this->getDoctrine_Orm_DefaultEntityManagerService()));
