<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'fos_rest.routing.loader.yaml_collection' shared service.

include_once \dirname(__DIR__, 4).'/vendor/symfony/config/Loader/LoaderInterface.php';
include_once \dirname(__DIR__, 4).'/vendor/symfony/config/Loader/Loader.php';
include_once \dirname(__DIR__, 4).'/vendor/symfony/config/Loader/FileLoader.php';
include_once \dirname(__DIR__, 4).'/vendor/symfony/routing/Loader/YamlFileLoader.php';
include_once \dirname(__DIR__, 4).'/vendor/friendsofsymfony/rest-bundle/Routing/Loader/RestYamlCollectionLoader.php';
include_once \dirname(__DIR__, 4).'/vendor/friendsofsymfony/rest-bundle/Routing/Loader/RestRouteProcessor.php';

return $this->privates['fos_rest.routing.loader.yaml_collection'] = new \FOS\RestBundle\Routing\Loader\RestYamlCollectionLoader(($this->privates['file_locator'] ?? $this->load('getFileLocatorService.php')), ($this->privates['fos_rest.routing.loader.processor'] ?? ($this->privates['fos_rest.routing.loader.processor'] = new \FOS\RestBundle\Routing\Loader\RestRouteProcessor())), true, ['json' => false, 'xml' => false, 'html' => true], NULL);
