<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'hateoas.serializer.json_hal' shared service.

include_once \dirname(__DIR__, 4).'/vendor/willdurand/hateoas/src/Hateoas/Serializer/JsonSerializerInterface.php';
include_once \dirname(__DIR__, 4).'/vendor/willdurand/hateoas/src/Hateoas/Serializer/JsonHalSerializer.php';

return $this->privates['hateoas.serializer.json_hal'] = new \Hateoas\Serializer\JsonHalSerializer();
