<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Liip\ImagineBundle\Controller\ImagineController' shared service.

include_once \dirname(__DIR__, 4).'/vendor/liip/imagine-bundle/Controller/ImagineController.php';
include_once \dirname(__DIR__, 4).'/vendor/liip/imagine-bundle/Config/Controller/ControllerConfig.php';

return $this->services['Liip\\ImagineBundle\\Controller\\ImagineController'] = new \Liip\ImagineBundle\Controller\ImagineController(($this->services['sylius.liip.filter_service'] ?? $this->load('getSylius_Liip_FilterServiceService.php')), ($this->services['liip_imagine.data.manager'] ?? $this->load('getLiipImagine_Data_ManagerService.php')), ($this->services['liip_imagine.cache.signer'] ?? ($this->services['liip_imagine.cache.signer'] = new \Liip\ImagineBundle\Imagine\Cache\Signer($this->getEnv('APP_SECRET')))), ($this->privates['liip_imagine.controller.config'] ?? ($this->privates['liip_imagine.controller.config'] = new \Liip\ImagineBundle\Config\Controller\ControllerConfig(301))));
