<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'liip_imagine.config.stack_collection' shared service.

include_once \dirname(__DIR__, 4).'/vendor/liip/imagine-bundle/Config/StackCollection.php';

return $this->services['liip_imagine.config.stack_collection'] = new \Liip\ImagineBundle\Config\StackCollection(($this->privates['liip_imagine.config.stack_builder'] ?? $this->load('getLiipImagine_Config_StackBuilderService.php')), $this->parameters['liip_imagine.filter_sets']);
