<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'nelmio_alice.generator.object_generator.simple' shared service.

include_once \dirname(__DIR__, 4).'/vendor/nelmio/alice/src/Generator/ObjectGeneratorInterface.php';
include_once \dirname(__DIR__, 4).'/vendor/nelmio/alice/src/IsAServiceTrait.php';
include_once \dirname(__DIR__, 4).'/vendor/nelmio/alice/src/Generator/ObjectGenerator/SimpleObjectGenerator.php';

return $this->privates['nelmio_alice.generator.object_generator.simple'] = new \Nelmio\Alice\Generator\ObjectGenerator\SimpleObjectGenerator(($this->privates['nelmio_alice.generator.resolver.value.registry'] ?? $this->load('getNelmioAlice_Generator_Resolver_Value_RegistryService.php')), ($this->privates['nelmio_alice.generator.instantiator.existing_instance'] ?? $this->load('getNelmioAlice_Generator_Instantiator_ExistingInstanceService.php')), ($this->privates['nelmio_alice.generator.hydrator.simple'] ?? $this->load('getNelmioAlice_Generator_Hydrator_SimpleService.php')), ($this->privates['nelmio_alice.generator.caller.simple'] ?? $this->load('getNelmioAlice_Generator_Caller_SimpleService.php')));
