<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'nelmio_alice.generator.caller.registry' shared service.

include_once \dirname(__DIR__, 4).'/vendor/nelmio/alice/src/Generator/Caller/CallProcessorInterface.php';
include_once \dirname(__DIR__, 4).'/vendor/nelmio/alice/src/IsAServiceTrait.php';
include_once \dirname(__DIR__, 4).'/vendor/nelmio/alice/src/Generator/Caller/CallProcessorRegistry.php';
include_once \dirname(__DIR__, 4).'/vendor/nelmio/alice/src/Generator/Caller/ChainableCallProcessorInterface.php';
include_once \dirname(__DIR__, 4).'/vendor/nelmio/alice/src/Generator/Caller/CallProcessorAwareInterface.php';
include_once \dirname(__DIR__, 4).'/vendor/nelmio/alice/src/Generator/Caller/Chainable/ConfiguratorMethodCallProcessor.php';
include_once \dirname(__DIR__, 4).'/vendor/nelmio/alice/src/Generator/Caller/Chainable/MethodCallWithReferenceProcessor.php';
include_once \dirname(__DIR__, 4).'/vendor/nelmio/alice/src/Generator/Caller/Chainable/OptionalMethodCallProcessor.php';
include_once \dirname(__DIR__, 4).'/vendor/nelmio/alice/src/Generator/Caller/Chainable/SimpleMethodCallProcessor.php';

return $this->privates['nelmio_alice.generator.caller.registry'] = new \Nelmio\Alice\Generator\Caller\CallProcessorRegistry([0 => ($this->privates['nelmio_alice.generator.caller.chainable.configurator_method_call'] ?? ($this->privates['nelmio_alice.generator.caller.chainable.configurator_method_call'] = new \Nelmio\Alice\Generator\Caller\Chainable\ConfiguratorMethodCallProcessor())), 1 => ($this->privates['nelmio_alice.generator.caller.chainable.method_call_with_reference'] ?? ($this->privates['nelmio_alice.generator.caller.chainable.method_call_with_reference'] = new \Nelmio\Alice\Generator\Caller\Chainable\MethodCallWithReferenceProcessor())), 2 => ($this->privates['nelmio_alice.generator.caller.chainable.optional_method_call'] ?? ($this->privates['nelmio_alice.generator.caller.chainable.optional_method_call'] = new \Nelmio\Alice\Generator\Caller\Chainable\OptionalMethodCallProcessor())), 3 => ($this->privates['nelmio_alice.generator.caller.chainable.simple_call'] ?? ($this->privates['nelmio_alice.generator.caller.chainable.simple_call'] = new \Nelmio\Alice\Generator\Caller\Chainable\SimpleMethodCallProcessor()))]);
