<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'nelmio_alice.fixture_builder.expression_language.parser.simple_parser' shared service.

include_once \dirname(__DIR__, 4).'/vendor/nelmio/alice/src/FixtureBuilder/ExpressionLanguage/ParserInterface.php';
include_once \dirname(__DIR__, 4).'/vendor/nelmio/alice/src/IsAServiceTrait.php';
include_once \dirname(__DIR__, 4).'/vendor/nelmio/alice/src/FixtureBuilder/ExpressionLanguage/Parser/SimpleParser.php';

return $this->privates['nelmio_alice.fixture_builder.expression_language.parser.simple_parser'] = new \Nelmio\Alice\FixtureBuilder\ExpressionLanguage\Parser\SimpleParser(($this->privates['nelmio_alice.fixture_builder.expression_language.lexer.empty_value_lexer'] ?? $this->load('getNelmioAlice_FixtureBuilder_ExpressionLanguage_Lexer_EmptyValueLexerService.php')), ($this->privates['nelmio_alice.fixture_builder.expression_language.parser.token_parser.registry'] ?? $this->load('getNelmioAlice_FixtureBuilder_ExpressionLanguage_Parser_TokenParser_RegistryService.php')));
