<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'nelmio_alice.generator.instantiator.resolver' shared service.

include_once \dirname(__DIR__, 4).'/vendor/nelmio/alice/src/Generator/InstantiatorInterface.php';
include_once \dirname(__DIR__, 4).'/vendor/nelmio/alice/src/Generator/ValueResolverAwareInterface.php';
include_once \dirname(__DIR__, 4).'/vendor/nelmio/alice/src/IsAServiceTrait.php';
include_once \dirname(__DIR__, 4).'/vendor/nelmio/alice/src/Generator/Instantiator/InstantiatorResolver.php';

return $this->privates['nelmio_alice.generator.instantiator.resolver'] = new \Nelmio\Alice\Generator\Instantiator\InstantiatorResolver(($this->privates['nelmio_alice.generator.instantiator.registry'] ?? $this->load('getNelmioAlice_Generator_Instantiator_RegistryService.php')));
