<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Sylius\Component\Product\Factory\ProductVariantFactoryInterface' shared service.

include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Component/Product/Factory/ProductVariantFactoryInterface.php';
include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Component/Product/Factory/ProductVariantFactory.php';

return $this->services['Sylius\\Component\\Product\\Factory\\ProductVariantFactoryInterface'] = new \Sylius\Component\Product\Factory\ProductVariantFactory(($this->privates['sylius.custom_factory.product_variant.inner'] ?? $this->load('getSylius_CustomFactory_ProductVariant_InnerService.php')));
