<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Sylius\Component\Core\Factory\PaymentMethodFactoryInterface' shared service.

include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Component/Core/Factory/PaymentMethodFactoryInterface.php';
include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Component/Core/Factory/PaymentMethodFactory.php';

return $this->services['Sylius\\Component\\Core\\Factory\\PaymentMethodFactoryInterface'] = new \Sylius\Component\Core\Factory\PaymentMethodFactory(($this->privates['sylius.custom_factory.payment_method.inner'] ?? $this->load('getSylius_CustomFactory_PaymentMethod_InnerService.php')), ($this->services['sylius.factory.gateway_config'] ?? ($this->services['sylius.factory.gateway_config'] = new \Sylius\Component\Resource\Factory\Factory('App\\Entity\\Payment\\GatewayConfig'))));
