<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Sylius\Component\Product\Factory\ProductFactoryInterface' shared service.

include_once \dirname(__DIR__, 4).'/vendor/sylius/resource-bundle/src/Component/Factory/TranslatableFactoryInterface.php';
include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Component/Product/Factory/ProductFactoryInterface.php';
include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Component/Product/Factory/ProductFactory.php';

return $this->services['Sylius\\Component\\Product\\Factory\\ProductFactoryInterface'] = new \Sylius\Component\Product\Factory\ProductFactory(($this->privates['sylius.custom_factory.product.inner'] ?? $this->load('getSylius_CustomFactory_Product_InnerService.php')), ($this->services['Sylius\\Component\\Product\\Factory\\ProductVariantFactoryInterface'] ?? $this->load('getProductVariantFactoryInterfaceService.php')));
