<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'routing.resolver' shared service.

include_once \dirname(__DIR__, 4).'/vendor/symfony/config/Loader/LoaderResolverInterface.php';
include_once \dirname(__DIR__, 4).'/vendor/symfony/config/Loader/LoaderResolver.php';

$this->privates['routing.resolver'] = $instance = new \Symfony\Component\Config\Loader\LoaderResolver();

$instance->addLoader(($this->privates['routing.loader.xml'] ?? $this->load('getRouting_Loader_XmlService.php')));
$instance->addLoader(($this->privates['routing.loader.yml'] ?? $this->load('getRouting_Loader_YmlService.php')));
$instance->addLoader(($this->privates['routing.loader.php'] ?? $this->load('getRouting_Loader_PhpService.php')));
$instance->addLoader(($this->privates['routing.loader.glob'] ?? $this->load('getRouting_Loader_GlobService.php')));
$instance->addLoader(($this->privates['routing.loader.directory'] ?? $this->load('getRouting_Loader_DirectoryService.php')));
$instance->addLoader(($this->privates['routing.loader.container'] ?? $this->load('getRouting_Loader_ContainerService.php')));
$instance->addLoader(($this->privates['sylius.routing.loader.resource'] ?? $this->load('getSylius_Routing_Loader_ResourceService.php')));
$instance->addLoader(($this->privates['fos_rest.routing.loader.directory'] ?? $this->load('getFosRest_Routing_Loader_DirectoryService.php')));
$instance->addLoader(($this->privates['fos_rest.routing.loader.controller'] ?? $this->load('getFosRest_Routing_Loader_ControllerService.php')));
$instance->addLoader(($this->privates['fos_rest.routing.loader.yaml_collection'] ?? $this->load('getFosRest_Routing_Loader_YamlCollectionService.php')));
$instance->addLoader(($this->privates['fos_rest.routing.loader.xml_collection'] ?? $this->load('getFosRest_Routing_Loader_XmlCollectionService.php')));
$instance->addLoader(($this->privates['sylius.sitemap.routing_loader'] ?? $this->load('getSylius_Sitemap_RoutingLoaderService.php')));
$instance->addLoader(($this->privates['routing.loader.annotation'] ?? $this->load('getRouting_Loader_AnnotationService.php')));
$instance->addLoader(($this->privates['routing.loader.annotation.directory'] ?? $this->load('getRouting_Loader_Annotation_DirectoryService.php')));
$instance->addLoader(($this->privates['routing.loader.annotation.file'] ?? $this->load('getRouting_Loader_Annotation_FileService.php')));

return $instance;
