<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sylius.behat.context.ui.shop.checkout.shipping' shared service.

include_once \dirname(__DIR__, 4).'/vendor/behat/behat/src/Behat/Behat/Context/Context.php';
include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Behat/Context/Ui/Shop/Checkout/CheckoutShippingContext.php';

return $this->services['sylius.behat.context.ui.shop.checkout.shipping'] = new \Sylius\Behat\Context\Ui\Shop\Checkout\CheckoutShippingContext(($this->privates['sylius.behat.page.shop.checkout.select_shipping'] ?? $this->load('getSylius_Behat_Page_Shop_Checkout_SelectShippingService.php')), ($this->privates['sylius.behat.page.shop.checkout.select_payment'] ?? $this->load('getSylius_Behat_Page_Shop_Checkout_SelectPaymentService.php')), ($this->privates['sylius.behat.page.shop.checkout.complete'] ?? $this->load('getSylius_Behat_Page_Shop_Checkout_CompleteService.php')));
