<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sylius.behat.channel_context_setter' shared service.

include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Behat/Service/Setter/ChannelContextSetterInterface.php';
include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Behat/Service/Setter/ChannelContextSetter.php';

return $this->privates['sylius.behat.channel_context_setter'] = new \Sylius\Behat\Service\Setter\ChannelContextSetter(($this->privates['sylius.behat.cookie_setter'] ?? $this->load('getSylius_Behat_CookieSetterService.php')));
