<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sylius.behat.context.ui.admin.impersonating_customers' shared service.

include_once \dirname(__DIR__, 4).'/vendor/behat/behat/src/Behat/Behat/Context/Context.php';
include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Behat/Context/Ui/Admin/ImpersonatingCustomersContext.php';

return $this->services['sylius.behat.context.ui.admin.impersonating_customers'] = new \Sylius\Behat\Context\Ui\Admin\ImpersonatingCustomersContext(($this->privates['sylius.behat.page.admin.customer.show'] ?? $this->load('getSylius_Behat_Page_Admin_Customer_ShowService.php')), ($this->privates['sylius.behat.page.admin.dashboard'] ?? $this->load('getSylius_Behat_Page_Admin_DashboardService.php')), ($this->privates['sylius.behat.page.shop.home'] ?? $this->load('getSylius_Behat_Page_Shop_HomeService.php')), ($this->privates['sylius.behat.page.admin.impersonate_user'] ?? $this->load('getSylius_Behat_Page_Admin_ImpersonateUserService.php')));
