<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sylius.sitemap_index_builder' shared service.

include_once \dirname(__DIR__, 4).'/vendor/stefandoorn/sitemap-plugin/src/Builder/BuilderInterface.php';
include_once \dirname(__DIR__, 4).'/vendor/stefandoorn/sitemap-plugin/src/Builder/SitemapIndexBuilderInterface.php';
include_once \dirname(__DIR__, 4).'/vendor/stefandoorn/sitemap-plugin/src/Builder/SitemapIndexBuilder.php';
include_once \dirname(__DIR__, 4).'/vendor/stefandoorn/sitemap-plugin/src/Factory/SitemapIndexFactoryInterface.php';
include_once \dirname(__DIR__, 4).'/vendor/stefandoorn/sitemap-plugin/src/Factory/SitemapIndexFactory.php';

$this->privates['sylius.sitemap_index_builder'] = $instance = new \SitemapPlugin\Builder\SitemapIndexBuilder(($this->privates['sylius.sitemap_index_factory'] ?? ($this->privates['sylius.sitemap_index_factory'] = new \SitemapPlugin\Factory\SitemapIndexFactory())));

$instance->addProvider(($this->privates['sylius.sitemap_provider.product'] ?? $this->load('getSylius_SitemapProvider_ProductService.php')));
$instance->addProvider(($this->privates['sylius.sitemap_provider.taxon'] ?? $this->load('getSylius_SitemapProvider_TaxonService.php')));
$instance->addProvider(($this->privates['sylius.sitemap_provider.static'] ?? $this->load('getSylius_SitemapProvider_StaticService.php')));
$instance->addIndexProvider(($this->privates['sylius.sitemap_index_provider.index'] ?? $this->load('getSylius_SitemapIndexProvider_IndexService.php')));

return $instance;
