<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sylius.controller.shop.locale_switch' shared service.

include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/ShopBundle/Controller/LocaleSwitchController.php';

return $this->services['sylius.controller.shop.locale_switch'] = new \Sylius\Bundle\ShopBundle\Controller\LocaleSwitchController(($this->services['templating'] ?? $this->load('getTemplatingService.php')), ($this->services['Sylius\\Component\\Locale\\Context\\LocaleContextInterface'] ?? $this->getLocaleContextInterfaceService()), ($this->services['sylius.locale_provider.channel_based'] ?? $this->getSylius_LocaleProvider_ChannelBasedService()), ($this->privates['sylius.shop.locale_switcher'] ?? $this->load('getSylius_Shop_LocaleSwitcherService.php')));
