<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sylius.behat.context.transform.promotion' shared service.

include_once \dirname(__DIR__, 4).'/vendor/behat/behat/src/Behat/Behat/Context/Context.php';
include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Behat/Context/Transform/PromotionContext.php';

return $this->services['sylius.behat.context.transform.promotion'] = new \Sylius\Behat\Context\Transform\PromotionContext(($this->services['sylius.repository.promotion'] ?? $this->load('getSylius_Repository_PromotionService.php')), ($this->services['sylius.repository.promotion_coupon'] ?? $this->load('getSylius_Repository_PromotionCouponService.php')));
