<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sylius.behat.context.ui.admin.move_to_edit_product_page' shared service.

include_once \dirname(__DIR__, 4).'/vendor/behat/behat/src/Behat/Behat/Context/Context.php';
include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Behat/Context/Ui/Admin/AccessingEditPageFromProductShowPageContext.php';

return $this->services['sylius.behat.context.ui.admin.move_to_edit_product_page'] = new \Sylius\Behat\Context\Ui\Admin\AccessingEditPageFromProductShowPageContext(($this->privates['sylius.behat.page.admin.product.update_simple'] ?? $this->load('getSylius_Behat_Page_Admin_Product_UpdateSimpleService.php')), ($this->privates['sylius.behat.page.admin.product_variant.update'] ?? $this->load('getSylius_Behat_Page_Admin_ProductVariant_UpdateService.php')));
