<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'security.firewall.map.context.shop' shared service.

include_once \dirname(__DIR__, 4).'/vendor/symfony/security-bundle/Security/FirewallContext.php';

return $this->privates['security.firewall.map.context.shop'] = new \Symfony\Bundle\SecurityBundle\Security\FirewallContext(new RewindableGenerator(function () {
    yield 0 => ($this->privates['security.channel_listener'] ?? $this->load('getSecurity_ChannelListenerService.php'));
    yield 1 => ($this->privates['security.context_listener.1'] ?? $this->load('getSecurity_ContextListener_1Service.php'));
    yield 2 => ($this->privates['security.authentication.listener.form.shop'] ?? $this->load('getSecurity_Authentication_Listener_Form_ShopService.php'));
    yield 3 => ($this->privates['security.authentication.listener.rememberme.shop'] ?? $this->load('getSecurity_Authentication_Listener_Rememberme_ShopService.php'));
    yield 4 => ($this->privates['security.authentication.listener.anonymous.shop'] ?? $this->load('getSecurity_Authentication_Listener_Anonymous_ShopService.php'));
    yield 5 => ($this->privates['security.authentication.switchuser_listener.shop'] ?? $this->load('getSecurity_Authentication_SwitchuserListener_ShopService.php'));
    yield 6 => ($this->privates['security.access_listener'] ?? $this->load('getSecurity_AccessListenerService.php'));
}, 7), ($this->privates['security.exception_listener.shop'] ?? $this->load('getSecurity_ExceptionListener_ShopService.php')), ($this->privates['security.logout_listener.shop'] ?? $this->load('getSecurity_LogoutListener_ShopService.php')), ($this->privates['security.firewall.map.config.shop'] ?? $this->load('getSecurity_Firewall_Map_Config_ShopService.php')));
