<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sylius.behat.context.setup.payment' shared service.

include_once \dirname(__DIR__, 4).'/vendor/behat/behat/src/Behat/Behat/Context/Context.php';
include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Behat/Context/Setup/PaymentContext.php';
include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Behat/Service/SharedStorageInterface.php';
include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Behat/Service/SharedStorage.php';

return $this->services['sylius.behat.context.setup.payment'] = new \Sylius\Behat\Context\Setup\PaymentContext(($this->privates['sylius.behat.shared_storage'] ?? ($this->privates['sylius.behat.shared_storage'] = new \Sylius\Behat\Service\SharedStorage())), ($this->services['sylius.repository.payment_method'] ?? $this->getSylius_Repository_PaymentMethodService()), ($this->services['sylius.fixture.example_factory.payment_method'] ?? $this->load('getSylius_Fixture_ExampleFactory_PaymentMethodService.php')), ($this->services['sylius.factory.payment_method_translation'] ?? ($this->services['sylius.factory.payment_method_translation'] = new \Sylius\Component\Resource\Factory\Factory('App\\Entity\\Payment\\PaymentMethodTranslation'))), ($this->services['doctrine.orm.default_entity_manager'] ?? $this->getDoctrine_Orm_DefaultEntityManagerService()), ['offline' => 'Offline', 'paypal_express_checkout' => 'Paypal Express Checkout', 'stripe_checkout' => 'Stripe Checkout']);
