<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sylius.behat.context.ui.shop.checkout.addressing' shared service.

include_once \dirname(__DIR__, 4).'/vendor/behat/behat/src/Behat/Behat/Context/Context.php';
include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Behat/Context/Ui/Shop/Checkout/CheckoutAddressingContext.php';
include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Behat/Service/SharedStorageInterface.php';
include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Behat/Service/SharedStorage.php';
include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Component/Addressing/Comparator/AddressComparatorInterface.php';
include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Component/Addressing/Comparator/AddressComparator.php';

return $this->services['sylius.behat.context.ui.shop.checkout.addressing'] = new \Sylius\Behat\Context\Ui\Shop\Checkout\CheckoutAddressingContext(($this->privates['sylius.behat.shared_storage'] ?? ($this->privates['sylius.behat.shared_storage'] = new \Sylius\Behat\Service\SharedStorage())), ($this->privates['sylius.behat.page.shop.checkout.address'] ?? $this->load('getSylius_Behat_Page_Shop_Checkout_AddressService.php')), ($this->services['sylius.factory.address'] ?? $this->load('getSylius_Factory_AddressService.php')), ($this->services['sylius.address_comparator'] ?? ($this->services['sylius.address_comparator'] = new \Sylius\Component\Addressing\Comparator\AddressComparator())), ($this->privates['sylius.behat.page.shop.checkout.select_shipping'] ?? $this->load('getSylius_Behat_Page_Shop_Checkout_SelectShippingService.php')));
