<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sylius.behat.context.ui.admin.managing_channels_billing_data' shared service.

include_once \dirname(__DIR__, 4).'/vendor/behat/behat/src/Behat/Behat/Context/Context.php';
include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Behat/Context/Ui/Admin/ManagingChannelsBillingDataContext.php';

return $this->services['sylius.behat.context.ui.admin.managing_channels_billing_data'] = new \Sylius\Behat\Context\Ui\Admin\ManagingChannelsBillingDataContext(($this->privates['sylius.behat.element.admin.channel.shop_billing_data'] ?? $this->load('getSylius_Behat_Element_Admin_Channel_ShopBillingDataService.php')));
