<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sylius.behat.context.domain.managing_orders' shared service.

include_once \dirname(__DIR__, 4).'/vendor/behat/behat/src/Behat/Behat/Context/Context.php';
include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Behat/Context/Domain/ManagingOrdersContext.php';
include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Behat/Service/SharedStorageInterface.php';
include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Behat/Service/SharedStorage.php';

return $this->services['sylius.behat.context.domain.managing_orders'] = new \Sylius\Behat\Context\Domain\ManagingOrdersContext(($this->privates['sylius.behat.shared_storage'] ?? ($this->privates['sylius.behat.shared_storage'] = new \Sylius\Behat\Service\SharedStorage())), ($this->services['sylius.repository.order'] ?? $this->getSylius_Repository_OrderService()), ($this->services['sylius.repository.order_item'] ?? $this->load('getSylius_Repository_OrderItemService.php')), ($this->services['sylius.repository.address'] ?? $this->load('getSylius_Repository_AddressService.php')), ($this->services['sylius.repository.adjustment'] ?? $this->load('getSylius_Repository_AdjustmentService.php')), ($this->services['doctrine.orm.default_entity_manager'] ?? $this->getDoctrine_Orm_DefaultEntityManagerService()), ($this->services['sylius.product_variant_resolver.default'] ?? ($this->services['sylius.product_variant_resolver.default'] = new \Sylius\Component\Product\Resolver\DefaultProductVariantResolver())), ($this->services['sylius.unpaid_orders_state_updater'] ?? $this->load('getSylius_UnpaidOrdersStateUpdaterService.php')));
