<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sylius.behat.context.ui.paypal' shared service.

include_once \dirname(__DIR__, 4).'/vendor/behat/behat/src/Behat/Behat/Context/Context.php';
include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Behat/Context/Ui/PaypalContext.php';

return $this->services['sylius.behat.context.ui.paypal'] = new \Sylius\Behat\Context\Ui\PaypalContext(($this->privates['sylius.behat.page.external.paypal_checkout_express'] ?? $this->load('getSylius_Behat_Page_External_PaypalCheckoutExpressService.php')), ($this->privates['sylius.behat.page.shop.order.show'] ?? $this->load('getSylius_Behat_Page_Shop_Order_ShowService.php')), ($this->privates['sylius.behat.page.shop.checkout.complete'] ?? $this->load('getSylius_Behat_Page_Shop_Checkout_CompleteService.php')), ($this->privates['sylius.behat.paypal_api_mocker'] ?? $this->load('getSylius_Behat_PaypalApiMockerService.php')));
