<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sylius.behat.context.domain.managing_shipments' shared service.

include_once \dirname(__DIR__, 4).'/vendor/behat/behat/src/Behat/Behat/Context/Context.php';
include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Behat/Context/Domain/ManagingShipmentsContext.php';

return $this->services['sylius.behat.context.domain.managing_shipments'] = new \Sylius\Behat\Context\Domain\ManagingShipmentsContext(($this->services['sylius.repository.shipment'] ?? $this->load('getSylius_Repository_ShipmentService.php')));
