<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sylius.behat.shared_security' shared service.

include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Behat/Service/SharedSecurityServiceInterface.php';
include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Behat/Service/SharedSecurityService.php';

return $this->privates['sylius.behat.shared_security'] = new \Sylius\Behat\Service\SharedSecurityService(($this->privates['sylius.behat.admin_security'] ?? $this->load('getSylius_Behat_AdminSecurityService.php')));
