<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sylius.behat.context.ui.admin.managing_payments' shared service.

include_once \dirname(__DIR__, 4).'/vendor/behat/behat/src/Behat/Behat/Context/Context.php';
include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Behat/Context/Ui/Admin/ManagingPaymentsContext.php';

return $this->services['sylius.behat.context.ui.admin.managing_payments'] = new \Sylius\Behat\Context\Ui\Admin\ManagingPaymentsContext(($this->privates['sylius.behat.page.admin.payment.index'] ?? $this->load('getSylius_Behat_Page_Admin_Payment_IndexService.php')), ($this->privates['sylius.behat.page.admin.order.show'] ?? $this->load('getSylius_Behat_Page_Admin_Order_ShowService.php')), ($this->privates['sylius.behat.notification_checker'] ?? $this->load('getSylius_Behat_NotificationCheckerService.php')));
