<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'security.firewall.map.config.api' shared service.

include_once \dirname(__DIR__, 4).'/vendor/symfony/security-bundle/Security/FirewallConfig.php';

return $this->privates['security.firewall.map.config.api'] = new \Symfony\Bundle\SecurityBundle\Security\FirewallConfig('api', 'security.user_checker', '.security.request_matcher.jsUtyW7', true, true, 'sylius.admin_user_provider.email_or_name_based', NULL, 'fos_oauth_server.security.entry_point', NULL, NULL, [0 => 'fos_oauth', 1 => 'anonymous'], NULL);
