<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sylius.behat.context.setup.shipping' shared service.

include_once \dirname(__DIR__, 4).'/vendor/behat/behat/src/Behat/Behat/Context/Context.php';
include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Behat/Context/Setup/ShippingContext.php';
include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Behat/Service/SharedStorageInterface.php';
include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Behat/Service/SharedStorage.php';

return $this->services['sylius.behat.context.setup.shipping'] = new \Sylius\Behat\Context\Setup\ShippingContext(($this->privates['sylius.behat.shared_storage'] ?? ($this->privates['sylius.behat.shared_storage'] = new \Sylius\Behat\Service\SharedStorage())), ($this->services['sylius.repository.shipping_method'] ?? $this->getSylius_Repository_ShippingMethodService()), ($this->services['sylius.repository.zone'] ?? $this->getSylius_Repository_ZoneService()), ($this->services['sylius.fixture.example_factory.shipping_method'] ?? $this->load('getSylius_Fixture_ExampleFactory_ShippingMethodService.php')), ($this->services['sylius.factory.shipping_method_translation'] ?? ($this->services['sylius.factory.shipping_method_translation'] = new \Sylius\Component\Resource\Factory\Factory('App\\Entity\\Shipping\\ShippingMethodTranslation'))), ($this->services['doctrine.orm.default_entity_manager'] ?? $this->getDoctrine_Orm_DefaultEntityManagerService()));
