<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Sylius\Behat\Context\Cli\ShowingAvailablePluginsContext' shared service.

include_once \dirname(__DIR__, 4).'/vendor/behat/behat/src/Behat/Behat/Context/Context.php';
include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Behat/Context/Cli/ShowingAvailablePluginsContext.php';

return $this->services['Sylius\\Behat\\Context\\Cli\\ShowingAvailablePluginsContext'] = new \Sylius\Behat\Context\Cli\ShowingAvailablePluginsContext(($this->services['kernel'] ?? $this->get('kernel', 1)));
