<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sylius.form.type.tax_calculation_strategy_choice' shared service.

include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/CoreBundle/Form/Type/TaxCalculationStrategyChoiceType.php';

return $this->services['sylius.form.type.tax_calculation_strategy_choice'] = new \Sylius\Bundle\CoreBundle\Form\Type\TaxCalculationStrategyChoiceType($this->parameters['sylius.tax_calculation_strategies']);
