<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Sylius\Bundle\CoreBundle\Security\UserImpersonatorInterface' shared service.

include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/CoreBundle/Security/UserImpersonatorInterface.php';
include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/CoreBundle/Security/UserImpersonator.php';

return $this->services['Sylius\\Bundle\\CoreBundle\\Security\\UserImpersonatorInterface'] = new \Sylius\Bundle\CoreBundle\Security\UserImpersonator(($this->services['session'] ?? $this->getSessionService()), 'shop', ($this->services['event_dispatcher'] ?? $this->getEventDispatcherService()));
