<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sylius.listener.shop_user_delete' shared service.

include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/UserBundle/EventListener/UserDeleteListener.php';

return $this->privates['sylius.listener.shop_user_delete'] = new \Sylius\Bundle\UserBundle\EventListener\UserDeleteListener(($this->services['security.token_storage'] ?? $this->getSecurity_TokenStorageService()), ($this->services['session'] ?? $this->getSessionService()));
