<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Sylius\Bundle\CoreBundle\Command\ShowAvailablePluginsCommand' shared service.

include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/CoreBundle/Command/ShowAvailablePluginsCommand.php';

return $this->services['Sylius\\Bundle\\CoreBundle\\Command\\ShowAvailablePluginsCommand'] = new \Sylius\Bundle\CoreBundle\Command\ShowAvailablePluginsCommand();
