<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGuBKvj0\srcApp_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGuBKvj0/srcApp_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerGuBKvj0.legacy');

    return;
}

if (!\class_exists(srcApp_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerGuBKvj0\srcApp_KernelTestDebugContainer::class, srcApp_KernelTestDebugContainer::class, false);
}

return new \ContainerGuBKvj0\srcApp_KernelTestDebugContainer([
    'container.build_hash' => 'GuBKvj0',
    'container.build_id' => '0021b299',
    'container.build_time' => 1598103502,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGuBKvj0');
